### ISSUE TITLE
[BUG] Sorting by release year takes ages.

### ISSUE THREAD

**Issue by mvegter** [Depressurizer/Depressurizer#102]

**Comment by mvegter** [comment]
Fixed in the next release.

**Comment by mvegter** [comment]
This should be fixed in the latest release.

**Comment by fgb-code** [comment]
somehow I end up getting a folder (year) with all the games in it now on alphabetical order. there's no categories by year.

**Comment by mvegter** [comment]
@fgb-code Could you create a new issue for this as I don't see the connection between sorting performance and your comment.
