### ISSUE TITLE
Roms added by Ice not appearing as non-Steam games

### ISSUE THREAD

**Issue by CyricPL** [Depressurizer/Depressurizer#102]
I have set my profile to include non-Steam games but all of the roms that Ice added to my library as games are not showing in Depressurizer.

**Comment by Theo47** [comment]
Can you upload your shortcuts.vdf file located at Steam\userdata\*number*\config?

**Comment by ShizCalev** [comment]
Just for the record, ice doesn't support the new category format and the devs have ceased support for it. Use steam rom manager instead.

**Comment by Theo47** [comment]
I am going to assume that the fault lies with Ice then and close this issue.
