### ISSUE TITLE
[BUG] No review score for any Steam Store language other than English.

### ISSUE THREAD

**Issue by bimzcy** [Depressurizer/Depressurizer#103]
10818 Games
10255 Unknown Review Score
563 Review Score

Steam Store Language in Settings of Depressurizer is Simplified Chinese（中文(中国)）.
Windows 10
Depressurizer 4.6.0

No problem for setting Steam Store Language to English.

![no review](https://user-images.githubusercontent.com/2244565/50488661-8f4dc700-0a3e-11e9-887a-ed0914db6c8c.jpg)

**Comment by mvegter** [comment]
@bimzcy This will be fixed in the next release!

**Comment by mvegter** [comment]
@bimzcy This should be fixed in the latest release. If this bug is still present in the latest release, please feel free to create a new issue with up-to-date information.
