### ISSUE TITLE
[Feature] BLAEO Support

### ISSUE THREAD

**Issue by jullebarge** [Depressurizer/Depressurizer#108]
Hi,

It would be nice if the tool was able to use the categories on [BLAEO ](http://backlog-deepness.rhcloud.com/) website to sync with Steam.
Is there a way to do that ?

**Comment by Theo47** [comment]
I think that this feels too specific to add.

Unlike the rest of the autocats, that you can use straight from the app, for this one you'd need to sign up to the BLAEO website and then use said site, before you can take advantage of this feature.

**Comment by mvegter** [comment]
@jullebarge BLAEO is currently invitation only which makes this a low priority feature.

**Comment by mvegter** [comment]
Closing due to limited amount of users and the access is at the moment invitation only.

If in the near future the amount of users increase and the access is public, then please reopen or comment on this issue.
