### ISSUE TITLE
[BUG] Category game counts incorrect

### ISSUE THREAD

**Issue by matttcooke** [Depressurizer/Depressurizer#115]
Looks like non-Steam shortcuts are being counted twice in the category game counts if they're present in both the loaded profile and the shortcuts.vdf.

**Comment by mvegter** [comment]
Will be fixed in the next release!

**Comment by matttcooke** [comment]
This is marked as fixed but wasn't. I probably didn't explain it properly. 

I launched a PR with a fix: https://github.com/Depressurizer/Depressurizer/pull/125
