### ISSUE TITLE
[BUG] AutoCat by platform settings not working

### ISSUE THREAD

**Issue by bantza** [Depressurizer/Depressurizer#118]
**Describe the bug**
Selecting included platforms in Edit AutoCats dialog does not have desired effect.

**To Reproduce**
Select only Windows platform in AutoCat by platform and see all platform categories created when running AutoCat.

**Expected behavior**
Only selected platforms should be used.

**Fix**
In AutoCatPlatform.cs / CategorizeGame(GameInfo game, Filter filter) when setting categories for a game code checks if platform "Windows" is selected for all platforms. Should check if the category being set is selected.

**Comment by mvegter** [comment]
Will be fixed in the next release!
