### ISSUE TITLE
[REQUEST] AutoCat when store flag is missing

### ISSUE THREAD

**Issue by Mhmmm** [Depressurizer/Depressurizer#119]
Basically, just like auto categorizing games with certain store flag, let us categorize games that doesn't have a certain flag (but can have other flags).
That way it would be possible to make categories like "No Steam Cloud Support", which would be useful for me.

**Comment by mvegter** [comment]
You could do this by using the Advanced Filter feature. Categorize the selected apps by Steam Cloud Support, Enable Advanced Filter, right click on the category for Steam Cloud support and right click on it. Select "Set Filter" and select "Exclude", CTRL + A and right click on any of the selected apps. Add Category and then new or if you already have a category for Non Steam Cloud support.

I'm aware that this is a work around but this will do the trick.

**Comment by Mhmmm** [comment]
Well, yeah, it worked, thanks!
