### ISSUE TITLE
[REQUEST] AutoCat for removed/pulled out games, and don't prompt or try to scrape them again

### ISSUE THREAD

**Issue by mchubby** [Depressurizer/Depressurizer#120]
Sometimes a game, content, bundle, etc is removed by while users who already own that content are still allowed to download it.

**Describe the AutoCat you'd like**
When scraping for a known deleted entry, do not prompt or attempt to scrape it again, plus add the entry to an appropriate AutoCat (Obsolete?)

**Describe how this can/should happen**
Example: https://store.steampowered.com/app/201700/
Trying to access the page redirects to the top page as if a fictive appid was requested. I do not know how it could be handled reliably (some API call?) except by blacklisting known identifiers.

Related pages like the news channel page, the community page, are still up for instance
https://store.steampowered.com/news/?appids=201700
https://steamcommunity.com/app/201700/

Edit: kind of similar to #52

**Comment by mvegter** [comment]
I'm going to close this as you can manually add those games to the ignore list. It might not be the most convenient way but it is functional.
