### ISSUE TITLE
[BUG] Library isn't complete

### ISSUE THREAD

**Issue by Quin452** [Depressurizer/Depressurizer#122]
**Describe the bug**
When opening the program, games are loaded, but not the entire library.
There isn't any software, and the games that are loaded in total to 90 (out of 365 games).
There doesn't seem to be any rhyme or reason, as some are installed, some are not; some are paid and others free, and also (for some reason) the Resi2 demo is included.

**To Reproduce**
Just importing the game library when opening.

**Expected behavior**
A complete list of my game library

**Desktop (please complete the following information):**
 - OS: Windows 10

Could it be because the games are installed on a separate drive to my steam profile?

**Comment by yago-esh** [comment]
Same happened to me, but with the games on my library that are shared with steam family

**Comment by bringonblink** [comment]
I have a similar issue, as far as i can see all my games (around 3000) get imported fine, but my category doesnt populate fully. For example i have a windows category and it only gets half filled

**Comment by mvegter** [comment]
This is part of the [Depressurizer (Premium) API](https://github.com/Depressurizer/Depressurizer#depressurizer-premium-api-), for the normal Depressurizer  using the Steam Store page scraper you will have to manually do this.
