### ISSUE TITLE
[REQUEST]Add Chinese to the software

### ISSUE THREAD

**Issue by yimouleng** [Depressurizer/Depressurizer#124]
Want to be able to add Chinese language UI to the software， Thank you

**Comment by mvegter** [comment]
You could install Visual Studio and open each window/form and update the string by selecting the target language in the option window. If this is what you mean?

**Comment by yfdyh000** [comment]
@yimouleng 提交 #156 了。字符串真多，费力不小，效果一般。
[Debug.zip](https://github.com/Depressurizer/Depressurizer/files/3587433/Debug.zip)
