### ISSUE TITLE
Wrong sorting order ?

### ISSUE THREAD

**Issue by TheMiziko** [Depressurizer/Depressurizer#127]
This is next issue I have. It basically looks like this : https://gyazo.com/7dba64420e6245631e49b83ef3f82a7e
my games sorted by HLTB time are with wrong order
Here are my autocast settings : https://gyazo.com/6194ab96b1bfbf5d20f131c52a0954c9
the 5-10 category should be after 0-5, but for no reason it's at the very end.
Is there any way to fix it or adjust it ?

**Comment by Theo47** [comment]
Steam sorts categories in alphabetical order so Depressurizer does the same.
That means that it compares both strings letter by letter until it finds one that differs. Then it sorts them based on that letter. In this case 2<5 so (HLTB) 20-50 appears before (HLTB) 5-10.
We can't change the sort order of steam so we can only work around it.
In this case you could add a 0 before 5-10 or add an extra space between (HLTB) and 5-10. 
1. `(HLTB) 05-10`
1. `(HLTB)<space><space>5-10`

**Comment by TheMiziko** [comment]
@Theo47 Well, thanks for the info :) such a shame they don't allow you to do manual category order.
