### ISSUE TITLE
[BUG] "Hours Played" AutoCat not working correctly

### ISSUE THREAD

**Issue by thePoark** [Depressurizer/Depressurizer#128]
**Describe the bug**
The newly-added "Hours Played" AutoCat doesn't seem to work correctly.  I've been testing for the past hour on my profile, creating 10 rules for different time ranges of play.  My game list correctly displays values in the "Hours Played" column, but any time I auto-categorize my library, all games are added to my 0-0.5 rule (instead of distributed throughout the 10 time range rules I've created), which is set as follows:
Min Hours: 0.0
Max Hours: 0.5

**To Reproduce**
1. Go to 'Profile > Edit AutoCats'
2. Click on 'Create'
3. Type a rule name. ('By Hours Played')
4. Select Type: 'Hours Played'
5. Type in Prefix field: '(Played) '
--Add several rules covering a range of time:
[1]
5. Click 'Add Rule'
6. Type Name: '0.0-0.5'
7. Type Min Hours: '0.0'
8. Type Max Hours: '0.5'
[2]
9. Click 'Add Rule'
10. Type Name: '0.5-1.0'
11. Type Min Hours: '0.5'
12. Type Max Hours: '1.0'
[3-10]
X. Repeated steps covering additional ranges, reaching up to Min: '50.0' to Max: '0.0' (unlimited).
13. Click on 'Save All Changes'
--
14. Click on '<All>' from list of categories to select all games in library.
15. Click checkbox (checked) 'By Hours Played' to select for Auto-Categorize.
16. Click on 'Auto-Categorize (1442 Apps)'

**Expected behavior**
Based on the values in the "Hours Played" column displayed in the main, I would expect up to 10 new categories to be created based on the rules previously defined.  Instead, all apps are assigned to the single category that is created after processed: '0.0-0.5'

**Screenshots**
![depressurizer_v4800_main](https://user-images.githubusercontent.com/8568059/53913276-971e7e80-4020-11e9-9829-a8bf513102aa.png)
![depressurizer_v4800_editautocats](https://user-images.githubusercontent.com/8568059/53913278-98e84200-4020-11e9-8514-90dd7c24f26e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1803
 -  .NET Version 4.7.03056
 - Depressurizer v4.8.0.0

**Additional context**
Please let me know if you have any questions or require clarification.  Looking forward to using this feature; thank you for adding it.  👍

**Comment by mvegter** [comment]
I'm able to reproduce this issue and going to look into it.

**Comment by mvegter** [comment]
This will be fixed in the next release!
