### ISSUE TITLE
Missing Release Date Data

### ISSUE THREAD

**Issue by quantumryan** [Depressurizer/Depressurizer#131]
I'm using 7.3.0, and running as Auto-Cat by Release Year, but a surprising number of my games fall into the unknown year category.

I understand that some games will have unknown release dates, like games that are no longer in the store, or other games like [Alice: Madness Returns](http://store.steampowered.com/app/19680/) that just don't have a release date on the store page, but I'm finding a number of games that are in the store don't have a Release Date in my database. For example, [Artemis Spaceship Bridge Simulator](http://store.steampowered.com/app/247350), [Beach Ball Valley](http://store.steampowered.com/app/454830), [Beast Boxing Turbo](http://store.steampowered.com/app/259490) and even [Super Meat Boy](http://store.steampowered.com/app/40800).

Is there something I might be doing wrong?

**Comment by Theo47** [comment]
No, there was something i was doing wrong.

Apparently i assumed all games had publishers when i was writing the regex for Release Date. So for games with no publishers, like the ones above, it didn't work properly.

Fixed now. 59c23509c12766a7ed5ffc00a830042cb33adef8
