### ISSUE TITLE
[BUG] ArgumentOutOfRangeException when opening database entry

### ISSUE THREAD

**Issue by j-oliveras** [Depressurizer/Depressurizer#131]
**Describe the bug**
In some cases, the web sourced date saved to a database entry can be negative and opening a it to see the details crash with a `ArgumentOutOfRangeException`. The call stack is
```
   en System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
   en Depressurizer.GameDBEntryDialog.InitializeFields(DatabaseEntry entry)
   en Depressurizer.GameDBEntryDialog.GameDBEntryForm_Load(Object sender, EventArgs e)
   en System.Windows.Forms.Form.OnLoad(EventArgs e)
   en System.Windows.Forms.Form.OnCreateControl()
   en System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   en System.Windows.Forms.Control.CreateControl()
   en System.Windows.Forms.Control.WmShowWindow(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   en System.Windows.Forms.Form.WmShowWindow(Message& m)
   en System.Windows.Forms.Form.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

The message error is the error trowed by a DateTimePicker when the date is not between `MinDate` and `MaxDate` with value '31/12/1969 23:00:01' (I don't copy the error message because is in Spanish).

**To Reproduce**
1. Open the database editor.
2. Open detail of an entry not web sourced.
3. Save without change anything.
4. Open it again.
5. App crashes.

**Expected behavior**
It should not crash.

**Desktop (please complete the following information):**
 - OS: Windows 10 1803 x64
 - Version 4.9.0.0
 -  .NET Version Windows Native NET Framework

**Additional context**
Probably is needed to live in a timezone with positive offset (I live on GTM+1). The value saved as web sourced in my case is `-3559` (my timezone offset minus a second).

**Solutions**
* To solve it, probably should be to make sure that the value used as parameter in `DateTimeOffset.FromUnixTimeSeconds` is not negative. In lines:
https://github.com/Depressurizer/Depressurizer/blob/bd0c153ba1128f20a64b06fc2affa30f8a401b24/src/Depressurizer/DBEdit/DlgGameDBEntry.cs#L134-L135

**Comment by mvegter** [comment]
Should be fixed in the latest release!
