### ISSUE TITLE
[BUG] Data for 'Adult Only' games is not scrapped

### ISSUE THREAD

**Issue by Psyborx** [Depressurizer/Depressurizer#132]
**Describe the bug**
Data for 'Adult Only' games is not scrapped

**To Reproduce**
1. Try to scrape any 'Adult Only' game like Boobs 'em up (https://store.steampowered.com/app/1024500/Boobs_em_up/)
2. No data will be scrapped

**Expected behavior**
Scrape game data

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v4.9.0.0
 -  .NET Version: 4.7.2

**Additional context**
It looks like to see the Steam page of 'Adult Only' games you need to be logged in, so maybe the ability to logging in the scrapper might help in this issue

**Comment by mvegter** [comment]
Well yes, requiring users to sign in for scraping 'Adult Only' pages would be a solution. But would you feel comfortable sharing (Steam) login credentials with an unknown party?

**Comment by Psyborx** [comment]
That's a good point but that's the only workaround I could think of :confused:

**Comment by TheKojukinator** [comment]
What's the likelihood of using https://steamdb.info? I looked up the above game on there (https://steamdb.info/app/1024500/) and they have plenty of data exposed on the website, can even see tags at the bottom when on the "Prices" tab.

Also, I believe this is the API to steamdb.info - https://steamapi.xpaw.me/

**Comment by mvegter** [comment]
@TheKojukinator steamdb.info does not have an API and the second link is a simplified web interface for the Steam web API, not to be confused with steamdb.

**Comment by mvegter** [comment]
This is part of the [Depressurizer (Premium) API](https://github.com/Depressurizer/Depressurizer#depressurizer-premium-api-), for the normal Depressurizer  using the Steam Store page scraper you will have to manually do this.
