### ISSUE TITLE
[BUG] Depressurizer displaying in wrong language despite setting

### ISSUE THREAD

**Issue by SpeedyD** [Depressurizer/Depressurizer#133]
My Depressurizer is partially translated to Dutch despite that the Program UI Language setting is set to English. As is the Steam Store Language setting.

This has been an issue for many previous versions, ever since the move to the current UI design.

When I set the Program UI Language to English, I expect the Program's UI to be completely in English. Not partially English, partially Dutch.

 - OS: Windows 7 Ultimate 64 bits (6. 1, build 7601)
 - Version: Depressurizer v4.9.0.0 (but also many versions earlier)
 -  .NET Version: .NET Framework 4.7.2 (Release 461814 on Win 7)

This issue also occurs on a laptop running Windows 8.1 64 bits, an earlier .NET Framework and an earlier version.

The common thread between the two Windows installations is that both of them have Dutch as system language, which is what I assume is causing the issue. Both of them have the Program UI Language set to English, however.

**Comment by mvegter** [comment]
Have you tried removing your settings file?

**Comment by SpeedyD** [comment]
As I mentioned, I have also tried this on a laptop. Fresh installation.

If the settings file is the reason, I have to question why it's also
displaying the wrong language on the laptop.

**Comment by mvegter** [comment]
Hi @SpeedyD , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.

**Comment by SpeedyD** [comment]
![Settings](https://user-images.githubusercontent.com/6922861/124114915-75592900-da6d-11eb-999b-5cd25bd8b87f.png)
![Version](https://user-images.githubusercontent.com/6922861/124115080-a5083100-da6d-11eb-98b8-1dbbbfd3cc1d.png)

@mvegter: _Two years_ after my initial bug report, it is absolutely still happening.
And the same applies to my laptop as well, even now, even on Windows 8.1.

And yes, despite my sighs, I _have_ removed the settings file on both machines since. Multiple times, in fact. It just ends up Dutch by default for some reason.

**But.** On the flip side, with Steam's Dynamic Collection system.. I have.. actually not used Depressurizer in a while. Which is partially why it took this long to respond to your message. But in my defense, you did take a while yourself.
