### ISSUE TITLE
Why does the database get reset between new versions?

### ISSUE THREAD

**Issue by SameMan76** [Depressurizer/Depressurizer#137]
Why does Depressurizer reset the database if I try to use the file form a previous version? This is very inconvenient as I have details of games which no longer have steam store pages, as well as the issues surrounding scrapping large numbers of games, I have over 4000 games and having to scrape them every update is problematic.

**Comment by mvegter** [comment]
From which version are you upgrading?

**Comment by SameMan76** [comment]
Any recent version. I added a bunch of games to the database in December last year, I think I was possibly uing 4.2-4.4 as the backed up db file I have is dated Dec 6th. When I updated to the new version at the beginning of the year it didn't keep my additions or the other games I had previously scrapped. I have observed this behaviour when updating when each new version arrives. I place the new exe in the folder with my existing database and run the exe, as it loads I see the file size of the database file goto 0 and then to the size of the file that is supplied in the archive and I have to scrape everything. Hope this helps explain my problem.

**Comment by mvegter** [comment]
You should check your settings, the max age of scraped games is 30 days. Meaning any games that have been scraped 30 days prior will be remove from the database.

**Comment by SameMan76** [comment]
I don't want to seem as if im ungratefull for the work you have put into Depressurizer, it is invalueble for managing a large steam library. I have tried to look at the source code but I'm unsure of how to setup Visual Studio properly to do this and get errors.

I would however question why would you remove the information if it is older than 30 days, is there any way of having an option to change this behaviour. Even if the information is old would it still not be relevant for most uses in Depressurizer, especially when games are removed from steam and no longer have a store page to be scraped. Could it be setup to perform the scrape and replace the info if there are changes but leave whats there if none are found or the store page no longer exsists, maybe marking those games in a way to exclude them from future scrapes.

**Comment by mvegter** [comment]
At this moment you could increase the number of days to more than a year (or even longer) in the settings menu.
