### ISSUE TITLE
7.4.0 Genre Autocats - Lots of new seemingly random cats, enabled by default. 

### ISSUE THREAD

**Issue by thefunkygibbon** [Depressurizer/Depressurizer#138]
As per title, in this version i am seeing a lot of cats for a bunch of "genres" like - 
"Andrew Hulshult"
"Baba Yaga Games"

No idea who any of these are, if they are dev houses then why the random selection?

And having them enabled by default has just messed up all of my cats (luckily didn't save it!)

Annoyingly I'm going to have to click on "uncheck all" and work out which out of the lot of them are the ones I was using before the update. :(

**Comment by CorruptComputer** [comment]
They aren't managed by Depressurizer, categories are pulled from the Steam store page for the game.

**Comment by Theo47** [comment]
In this case though, it is Depressurizer's fault.

The regex used for scraping genres from steam store wasn't specific enough.
So if a game had no genre, it would match the developer instead and add that as genre.

I'll post a fix tomorrow.

**Comment by Theo47** [comment]
Fixed. e748c2ecc3315cd29ef3bbb4cef7a943158168ad

And made a new release. [v0.7.4.1](https://github.com/Depressurizer/Depressurizer/releases/tag/v0.7.4.1)

**Comment by thefunkygibbon** [comment]
awesome, thank you, will try shortly.

**Comment by CorruptComputer** [comment]
https://stackoverflow.com/a/1732454
