### ISSUE TITLE
Mono Support

### ISSUE THREAD

**Issue by mvegter** [Depressurizer/Depressurizer#14]

**Comment by alexey-zaharchenko** [comment]
Hi, any progress?

**Comment by mvegter** [comment]
@alexey-zaharchenko Difficult to anwser. Short: No. Right now the DepressurizerCore is mono supported, this is ~75% of the logic. Meaning that there is a remaining ~25% of logic in the Depressurizer project. 

If all critical logic is integrated in the DepressurizerCore project then you could make a different project for Linux / Mac UI and use the logic in DepressurizerCore. The main Depressurizer is not yet compatible with  mono as MaterialSkin doesn't support Mono and there are a few other issues.

**Comment by brianmaher84** [comment]
Maybe someone could consider doing a QT front end for this as then it would be cross platform.  Might be a big investment in time though but I am playing with PyQT at the moment for another project.

I stumbled upon the project looking to rename the new Resident Evil 7 game.  Great project BTW, I like it.

**Comment by mvegter** [comment]
Closing this issue after a prolonged period of inactivity.

**Comment by frostworx** [comment]
No native port, but you might want to know that I [just added](https://github.com/frostworx/steamtinkerlaunch/commit/27a56322032476a2eb1d2b1e92a5cd3ecee98127) Depressurizer support *(using proton/wine)* to my linux swiss army knife steam tool [steamtinkerlaunch](https://github.com/frostworx/steamtinkerlaunch) *([wiki entry](https://github.com/frostworx/steamtinkerlaunch/wiki/Depressurizer))*
