### ISSUE TITLE
[BUG] "Exception thrown in thread" error in Database Editor when attempting to "Scrape Unscraped"

### ISSUE THREAD

**Issue by HBNayr** [Depressurizer/Depressurizer#140]
**Describe the bug**
When attempting to update the database per the wiki, the program will pause for several seconds after clicking on "Scrape Unscraped", before throwing out the error message "Exception thrown in thread, stopping..."

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Database Editor'
3. Click on 'Scrape Unscraped'
4. Wait
5. See error

**Expected behavior**
I expected the program the program to finish scraping the unscraped games successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/49926437/56622372-5c36d100-65f5-11e9-86df-6aff6b8c699a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: Depressurizer v4.10.0.0
 -  .NET Version: .NET Framework 4.7.2

**Additional context**
The same problem does not occur for me when running Depressurizer v4.9.0.0 or v4.8.0.0.  It only happens with v4.10.0.0.

Thanks for your time and consideration, and all your effort!

**Comment by mvegter** [comment]
This is most likely due to scraping too many games at once. Steam will start slowing down (and denying) any new calls to the store. This is just a simple DDoS protection like system, thus nothing to do with Depressurizer.
