### ISSUE TITLE
[BUG] Timeout on downloading profile data

### ISSUE THREAD

**Issue by DragRedSim** [Depressurizer/Depressurizer#141]
**Describe the bug**
Depressurizer reports that the profile data cannot be downloaded with a timeout.

**To Reproduce**
1. Launch Depressurizer.
2. Wait for profile update.
3. Receive error message.

**Expected behavior**
Depressurizer launches without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/5095074/56866807-26448300-6a21-11e9-9b1a-580ea8fd0580.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1809 (all patches as of 29 April)
 -  .NET Version 4.7.3190.0

**Additional context**
I have a very large number of games on my account (Steam reports 9195 entries). I attempted to download the XML from https://steamcommunity.com/profiles/76561198004390798/games?tab=all&xml=1, but it reported a Gateway Timeout after four minutes.

It may be worth considering moving to the Steam Web API function [GetOwnedGames](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetOwnedGames_.28v0001.29), as the API being used is described as being deprecated at [the Valve API website](https://partner.steamgames.com/documentation/community_data). This alternate API returned the appropriate data in just over one second from triggering a load in the web browser, however it does require the usage of API keys to access data for private profiles.

**Comment by azumukupoe** [comment]
I've started to seeing this error since the latest update.

**Comment by mvegter** [comment]
This should be fixed / better handled in the next release, feel free to re-open or create a new issue of this problems still exists.
