### ISSUE TITLE
[BUG]Error encountered when updating database from HTLB

### ISSUE THREAD

**Issue by wellkens** [Depressurizer/Depressurizer#142]
Every time I run depressurizer, it pops up two warning windows.

![1](https://user-images.githubusercontent.com/22547715/58103874-52b18080-7c16-11e9-8029-16c6958de4bb.png)

![2](https://user-images.githubusercontent.com/22547715/58103899-61983300-7c16-11e9-8231-3c6e273630b7.png)

I don't know if HLTB is howlongtobeat.com which I can visit.

There is also a issue on the Edit Profile window. The "?" appears in the wrong position.

![3](https://user-images.githubusercontent.com/22547715/58105385-01ef5700-7c19-11e9-8ea3-b43a2f30d955.png)

Program Version: 4.10.0.0
OS: WIN10

**Comment by wellkens** [comment]
Nobody answer?

**Comment by mvegter** [comment]
@wellkens The API of howlongtobeat seems to be down:
> https://www.howlongtobeatsteam.com/api/games/library/cached

**Comment by wellkens** [comment]
@mvegter I can't visit, request was refused, HTTP ERROR 403
Dose it effect on using?

**Comment by Glamurio** [comment]
Yeah, I'm running into the same error message.

Edit: Managed to get it fixed, the issue ended up being a Japanese Region Locale, the screenshot tipped me off to trying to change it back to something else, and it worked. So you might want to do a check regarding the system locale to prevent this issue.
