### ISSUE TITLE
[BUG] Achievement count 0

### ISSUE THREAD

**Issue by DataCZ** [Depressurizer/Depressurizer#145]
All but one of my games with 100% Achievement progress are showing 0 achievement count. I'm 100% sure that they have at least 1 achievement. May be it's related to HUGE amount of items.
`<All>(2337)`

**Comment by mvegter** [comment]
Hi @DataCZ , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.
