### ISSUE TITLE
[REQUEST] Use the HowLongToBeat API to get playtime data insted of howlongtobeatsteam.com

### ISSUE THREAD

**Issue by hreffero** [Depressurizer/Depressurizer#147]
Use the HowLongToBeat API to get playtime data https://github.com/ckatzorke/howlongtobeat

The current code uses howlongtobeatsteam.com to get playtime data and there are several wrong sections, games are wrongly organized, and some of them have way off data.

 HowLongToBeat.com is more precise and has more accurate current data available

**Comment by mendhak** [comment]
It looks like the current code uses the URL

    https://www.howlongtobeatsteam.com/api/games/library/cached/all

and unfortunately that URL keeps erroring, while the Depressurizer code silently handles the error - presumably that URL fails frequently enough that it needed to be handled in this way.

https://github.com/Depressurizer/Depressurizer/blob/a83e330c8891ca1bd55017e692921c62f38140d5/src/Depressurizer/Database.cs#L734-L739


The ckatzorke/howlongtobeat API is an npm package, and this project is C# so it won't be easily usable.

However that npm package is  [an HTML scraper anyway](https://github.com/ckatzorke/howlongtobeat/tree/master/src/main).  So it could be that with a bit of studying the scraping can be replicated.   From some searching around the web this looks like the only way to get data off HLTB as they don't have an official API.

**Comment by Drexl** [comment]
Not sure if this is related, but in version 4.12.1.0 I'm trying to organize by HLTB and they all 929 games get tagged as unknown. This data clearly isn't getting scrapped correctly.

Edit: This is only happening when I provide a steam API key.

**Comment by mvegter** [comment]
The howlongtobeatsteam.com API uses howlongtobeat.com, if you are experencing any issues please report them here: https://github.com/ohadschn/HowLongToBeatSteam
