### ISSUE TITLE
[BUG] Exception thrown while scraping game data

### ISSUE THREAD

**Issue by SkyNinja** [Depressurizer/Depressurizer#149]
**Describe the bug**
When trying to scrape game data, an exception is thrown after only a few items. 

**To Reproduce**
1. Click "Autocategorize".
2. Click "Yes" when asked to scrape.
3. Wait a few seconds.

**Expected behavior**
Items are scraped.

**Screenshot**
![2019-06-30 (1)](https://user-images.githubusercontent.com/4765557/60394714-6215ca80-9aee-11e9-9125-c39a85acad1a.png)

**Desktop:**
 - OS: Windows 10 Pro
 - v1803
 -  .NET Version 4.7.2

**Comment by SkyNinja** [comment]
Well, I can't scrape anything anymore. This project is obviously dead.
The worst thing is, this wouldn't make the software totally unusable if it were handled better. The "Stop" and "Cancel" buttons don't work, and no matter what, this hangs the entire program, sometimes for almost fifteen minutes. **That** is what makes the software unusable.

**Comment by AndrewSav** [comment]
@SkyNinja works here. Perhaps something is wrong with your connection? Or firewall? Or antivirus? Or may be just steam API is playing up, may be try now and it works?

**Comment by mvegter** [comment]
@SkyNinja Steam will give send timeouts if you are scraping to many pages in a short period of time. Try scraping less games at a time and wait for X time between those scraping sessions.

**Comment by AndrewSav** [comment]
@mvegter is it possible to process those timeouts better, so that we do not have a modal window with two disabled buttons that user cannot close?

**Comment by mvegter** [comment]
@AndrewSav those two buttons are disabled so that the form can let the other threads properly close and merge the scraped data in the database.

**Comment by AndrewSav** [comment]
@mvegter, how long do you think properly closing and merging the scraped data takes? Approxiamtely.

**Comment by mvegter** [comment]
This should be fixed / better handled in the next release, feel free to re-open or create a new issue of this problems still exists.

**Comment by Hellcommander** [comment]
still encountering this scraping issue though at least it does hang or 15 mins for me (a few secs or so for it to finish stopping)
