### ISSUE TITLE
[REQUEST] Export to excel file .xlsx or .ods for share my steam library

### ISSUE THREAD

**Issue by Caiuzx** [Depressurizer/Depressurizer#150]
as title, export to excel file or libre office files ods - spreedsheet for share my library for trade etc. example on steamtrades and also an option to compare the various files in order to know which ones I have and I don't have to exchange: D (the another trade export the txt library that i compare on my depresserizer )
and also a coffee: D

**Comment by mvegter** [comment]
Hi @Caiuzx , thanks for your request. I do not see this fit for Depressurizer.
