### ISSUE TITLE
[BUG] "Software" advanced filter "Allowed" doesn't work

### ISSUE THREAD

**Issue by jakubdabek** [Depressurizer/Depressurizer#152]
**Describe the bug**
`Allowed` advanced filter doesn't work with `Software` category

**To Reproduce**
1. Click on `Advanced Filter`
2. Select `Software` category
3. Nothing happens

**Expected behavior**
List of only `Software` items should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/29653525/63549108-0dac2b80-c530-11e9-9a96-c87dc5e494f1.png)
Only `Software`:  
![image](https://user-images.githubusercontent.com/29653525/63549130-1997ed80-c530-11e9-91b6-23ed0159eafb.png)
Any other category:  
![image](https://user-images.githubusercontent.com/29653525/63549356-88754680-c530-11e9-8b5f-f8c49d7ee09f.png)

With `Required`:  
![image](https://user-images.githubusercontent.com/29653525/63549155-26b4dc80-c530-11e9-97cd-551a325c3014.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 4.10.0.0

**Additional context**
https://github.com/Depressurizer/Depressurizer/blob/0dc90e087e6104a66fa38826ce3c1483eca915ca/src/Depressurizer.Core/Models/Filter.cs#L105

**Comment by mvegter** [comment]
This should be fixed / better handled in the next release, feel free to re-open or create a new issue of this problems still exists.
