### ISSUE TITLE
[QA]  how to uninstall/remove?

### ISSUE THREAD

**Issue by alenknight** [Depressurizer/Depressurizer#153]
how do i uninstall/remove this? i want to start fresh, but when i just delete the DEPRESSURIZER folder, and re-download... it has all the old info.... 
if i look in windows/uninstall.. .it's not listed there.

**Comment by mvegter** [comment]
You should remove the AppData folder as well. Go to your file explorer and in the URL like bar type: %appdata%, you should find a Depressurizer folder.
