### ISSUE TITLE
[BUG] Steam web key is not saved, and the "SteamKeyDialog" is not modal

### ISSUE THREAD

**Issue by yfdyh000** [Depressurizer/Depressurizer#159]
**Describe the bug**
As title.

**To Reproduce**
1. Start Depressurizer v4.12.1, whether or not to create a profile.
2. Wait, you may manipulate other windows (like Browser, in maximized) at the same time, which may miss the Depressurizer window(s).
3. Apply and fill the Steam web key.
3. Close and restart Depressurizer.
4. Clicking the Stop button in the download games list window when the key is asked.

**Expected behavior**
1. N/A
2. Re-enable this.ShowIcon and ShowInTaskbar alleviates this problem, but if you can show the main window and then load the profile (`LoadProfile(Settings.ProfileToLoad, false);` in `FormMain_Load`), it would be better.
3. If you can explain its utility and delay the filling of the key (like option on profile), it is friendly to newer users.
3. You are asked again about the key, it is not saved, it is troublesome.
4. It work, though it does not continue. This may be because `ShowDialog()` in `\src\Depressurizer\CDlgUpdateProfile.cs`, and it is called by `LoadProfile` from `FormMain_Load`, the main form is not loaded.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v4.12.1
 -  .NET Version 4.7

**Comment by yfdyh000** [comment]
It is also possible because CancelableDialog.cs is not modal.

**Comment by mvegter** [comment]
Hi @yfdyh000 , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) as this should have been fixed.
