### ISSUE TITLE
[BUG] Fatal Error editing autocat

### ISSUE THREAD

**Issue by arnili** [Depressurizer/Depressurizer#163]
**Describe the bug**
Editing autocat from an old profile causes fatal error, program will terminate

**To Reproduce**
1.: EDIT AUTOCATS
2.: Select this autocat from the list

**Expected behavior**
Beeing able to at least view the autocat and fix the offending value

**Screenshots**
System.ArgumentOutOfRangeException: Der Wert 15 ist für Value ungültig. Value sollte zwischen 'Minimum' und 'Maximum' liegen.
Parametername: Value
   bei System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   bei Depressurizer.AutoCats.AutoCatConfigPanel_Tags.LoadFromAutoCat(AutoCat autoCat)
   bei Depressurizer.DlgAutoCat.FillConfigPanel()
   bei Depressurizer.DlgAutoCat.lstAutoCats_SelectedIndexChanged(Object sender, EventArgs e)
   bei System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   bei System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ListBox.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Desktop (please complete the following information):**
 - OS: Windows 10 1604
 - Version: 4.12.1.0

**Additional context**
-

**Comment by mvegter** [comment]
Hi @arnili , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.
