### ISSUE TITLE
Categories ending with a "?" are not clickable in Steam Library BETA

### ISSUE THREAD

**Issue by Drexl** [Depressurizer/Depressurizer#167]
I'm not having any of the other issues people seem to be having with the beta. My categories were not deleted. However, if any of them end with a ? and were generated using depressurizer I can't select them. If I create a category in steam and end it with a ? it works fine.

**Comment by Njbud13** [comment]
I reported this to Steam and they concluded that they will probably not fix it on their end.
This is not something that can be fixed from Depressurizers end either.
You just have to be aware that using ? in categories will cause issues.

**Comment by mvegter** [comment]
This is something for Steam to resolve
