### ISSUE TITLE
[REQUEST] Ship Depressurizer with a filled DB

### ISSUE THREAD

**Issue by Qubits01** [Depressurizer/Depressurizer#168]
The problem I have is that scraping my 8000+ games will take forever because as of now scraping will crash with an exception after a few dozen games read (known issue from what I've read).

Won't it be possible that depressurizer has a database included? Maybe there could be a possibility for users to submit their databases and then merge them.

Seems like a cool tool, but unusable for me at the moment, sadly.

**Comment by mvegter** [comment]
This is part of the [Depressurizer (Premium) API](https://github.com/Depressurizer/Depressurizer#depressurizer-premium-api-), for the normal Depressurizer  using the Steam Store page scraper you will have to manage this yourself.
