### ISSUE TITLE
[BUG][v4.12.1] Categories are not applied to Steam Beta Client

### ISSUE THREAD

**Issue by Poofey** [Depressurizer/Depressurizer#169]
**Describe the bug**
After saving the profile and verifying the file is in the userdata folder, starting Steam Beta will not show the new categories. 

**To Reproduce**
1. Close Steam
2. Save profile
3. Open Steam

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by AlJoelson** [comment]
Things seemed to be working okay for me the day before but all of a sudden, it's no longer working.

**Comment by halbet** [comment]
Solution here: https://github.com/Depressurizer/Depressurizer/issues/165

To re-import your old categories into the Beta do the following with the Steam Client open and running the Beta:

Bring up the run window by holding Windows key and the r key
Put the following command into the run window's input box: steam://resetcollections
You will get a warning message that any new collections you made will be lost while re-importing your old categories. Selecting OK to continue.

**Comment by Kakise** [comment]
This problem also occur with the latest steam client. The fix on the message before me works

**Comment by SpaceModulator** [comment]
Is this something that can be fixed? I would hate to think that the new version of steam has had such a huge and permanent effect on Depressurizer.

**Comment by ToughestMonk** [comment]
Tried ths: https://github.com/Depressurizer/Depressurizer/issues/169#issuecomment-538007222
When I use steam://resetcollections my Steam client offers to reset exact categories that I set in the Depressurizer [1 on the screenshot], but I still can't see theese categories in the Steam library itself - there is still my old hand-made categories [2 on the screenshot].
![steam_2020-05-03_01-02-01](https://user-images.githubusercontent.com/6598369/80893409-ab204780-8cda-11ea-9c0d-ee9d6caf7fb6.png)
