### ISSUE TITLE
Mention Domain Name for Steam Web API Key

### ISSUE THREAD

**Issue by ithinkandicode** [Depressurizer/Depressurizer#173]
**Is your feature request related to a problem? Please describe.**

The dialog to enter a Steam Web API key links to Steam's API page, which asks for a domain name, but I don't know what to enter

**Describe the solution you'd like**

Could the dialog have a copy + paste domain name please?

I tried this: http://api.steampowered.com/ - via the constant [here](https://github.com/Depressurizer/Depressurizer/blob/master/src/Depressurizer.Core/Helpers/Constants.cs#L30) - But my profile is public so I don't think the key is needed, so I can't check if this worked

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by shakeyourbunny** [comment]
The domain name does not matter as long as you are not using your API key for a real website.

**Comment by qs-arno** [comment]
For what it's worth: I don't remember what I actually did when I set up my Web API key a long time ago, but I can tell you that when I went and looked it up to provide it to Depressurizer, it showed the "domain" for it, which was `this_key_is_for_personal_use`.  Not sure if I actually entered that string or if I clicked a checkbox to that effect and that was the result...but that's what it says now.
