### ISSUE TITLE
Error Updating Local Files

### ISSUE THREAD

**Issue by Nikralx** [Depressurizer/Depressurizer#174]
Whenever I try to update the database, i get the error:

Error Updating from Local Files:
The given key was not present in the dictionary.

As far as I know everything is setup properly, even tried running as Administrator. 
Tried brand new profiles and everything, still getting that error.

**Comment by mvegter** [comment]
Hi @Nikralx , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.
