### ISSUE TITLE
[BUG] The numbers next to lists are very buggy

### ISSUE THREAD

**Issue by Ptival** [Depressurizer/Depressurizer#177]
**Describe the bug**
I just run Auto-categorize By User Score on my 3000 games library

**To Reproduce**
1. Click <All>
2. Click Auto-categorize after having selected "By User Score"

**Expected behavior**
The numbers next to the categories correspond to the number of items in those categories

Instead some show (0) when they have thousands of games, and if I start drag-and-dropping items around, I even get (-1000) once I re-run auto-categorize. The numbers just become completely wrong.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.12.1

**Comment by mvegter** [comment]
Hi @Ptival , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.
