### ISSUE TITLE
[BUG] Depressurizer doesn't work on the latest steam

### ISSUE THREAD

**Issue by DreadWolf-sketch** [Depressurizer/Depressurizer#178]
**Describe the bug**
Depressurizer works on old ui of steam but on new it does not

**To Reproduce**
1. download latest steam

**Expected behavior**
for it to work

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by cr45hmurphy** [comment]
I have also replicated this issue. I'm currently using Steam Package 1596762082.

It seems that the new Steam library layout does not automatically pull in changes made to the sharedconfig.vdf file. This is my hunch, at least. 

I believe I have found a temporary solution:

1. Close Steam
2. Save Depressurizer profile
3. Open Steam
4. Press Win+R
5. Type in: steam://resetcollections
6. A prompt will appear within the Steam window. Choose "Yes".
7. Library categories should be updated.

This has been my experience so far. It's crude, to say the least. I'm wondering if there is some way to incorporate this command within the save function (I'm sure there is). It would seem that Valve is trying to provide their own "categories/collections" by now offering dynamic collections. I'm sure the library still works off of the sharedconfig.vdf, but I am unsure of to what extent.

**Comment by ghost** [comment]
The solution worked for me exactly once.  
The situation was the typical one where changes in Depressurizer are not reflected in Steam. I checked the vdf file and it had the changes in it. With the special Steam command, they finally showed up in Steam.

But now I have the reverse problem. 
I did some sorting in Steam and then went back to Depressurizer. All the changes I made in Steam don't show up. I basically get the version I initially exported from DP.  
I tried everything to reset the situation. I deleted the DP settings folder. I deleted Steam userdata. But for some reason Steam downloads the old vdf without the changes.

**Comment by vinanrra** [comment]
Its working perfect with @cr45hmurphy steps.
