### ISSUE TITLE
[BUG] Unable to scrape data for game that have no store page

### ISSUE THREAD

**Issue by FenghuangZero** [Depressurizer/Depressurizer#180]
**Describe the bug**
When scraping web-data to update database, I have 90+ games that fail to update. These include multiplayer beta branches for working games, games that have been re-released as Director's Cut/GOTY versions, demos and open betas that have been taken down as the full game released, and games that have been removed from the steam store due to multiplayer services being discontinued.

**To Reproduce**
1. Own any game with the above conditions.
Examples include: Tom Clancy's Rainbow Six Siege - Test Server (AppID 623990); Rust - Staging Branch (AppID 700580); PlanetSide 2 - Test (AppID 1083500); Deus Ex: Human Revolution - The Missing Link (Standalone version, AppID 201280); Metro 2033 (AppID 43110); The Ship Tutorial (AppID 2430); Grand Theft Auto III (AppID 12230)

2. Scrape Unscraped from the Database Editor, or when prompted by Auto-Categorize

**Expected behavior**
While unscraped, these games will not display Tags, Review Score, Release Year and other properties, and cannot be auto-categorized. 
Historical records of this information can often be found at https://steamdb.info/

**Comment by Tythesly** [comment]
It would be cool if it could pull this data from steamdb.info if this happens.

**Comment by mvegter** [comment]
See https://github.com/Depressurizer/Depressurizer/issues/189#issuecomment-863898602
