### ISSUE TITLE
Autocat for genre and tags empty[BUG]

### ISSUE THREAD

**Issue by dogbri** [Depressurizer/Depressurizer#181]
Since a while the autocat für genre and tags is empty. all genres and all tags are gone. 
There is no reset to defaults - so i have to manually fill all the genres and tags - ??

**Comment by Shea1550** [comment]
I don't know enough to fix your problem, but the same thing happened to me a while back, and I made due by reverting to an earlier version. Several months later, I tried the newest version again, and it was working.

**Comment by mvegter** [comment]
Hi @dogbri , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.
