### ISSUE TITLE
[REQUEST] Random Game Selection and Launch

### ISSUE THREAD

**Issue by tidusiscariot** [Depressurizer/Depressurizer#185]
**Is your feature request related to a problem? Please describe.**
This is not really addressing any functional problem.  This is more designed to further alleviate  the condition of option overload.  Instead of having to choose what game to play, filter a list in any way you deem appropriate and have the application randomly select one for you.

**Describe the solution you'd like**
A menu item under the Tools menu to load a dialog box with the name and/or banner of a random game from the currently filtered game list.  This dialog will have a "cancel" button as well as a "load game" button.

**Describe alternatives you've considered**
I have not considered any as of yet, but am definitely open to other solutions.

**Additional context**
I have added this feature in a Fork of this repository.  If you'd like to review it:
https://github.com/tidusiscariot/Depressurizer-1/tree/feature/RandomGameSelection

**Comment by mvegter** [comment]
Hi @tidusiscariot , thanks for adding a new feature. Please consider opening a Pull Request instead of a issue for this.
