### ISSUE TITLE
[REQUEST] ability to auto-categorize mods for games within steam

### ISSUE THREAD

**Issue by staticanimal** [Depressurizer/Depressurizer#186]
**Is your feature request related to a problem? Please describe.**
i have roughly 430 mods for the half life games, the portal games and team fortress 2 installed. i'd like to have them categorized but steam keeps shuffling all of them around within the categories i assign them to in steam, making redoing the categories a slow and painfully boring process.

**Describe the solution you'd like**
i'd love to have a "mod" autocat, preferably with a dropdown menu that also lets you pick which game the mod is for, specifically

**Describe alternatives you've considered**
other than manually doing it, there are none. this is a niche issue that no one else has cared to take on.

**Additional context**
N/A

**Comment by mvegter** [comment]
Hi @GL1TCH04 , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is resolved for you
.
