### ISSUE TITLE
[REQUEST] Use Steam Database for removed games / software / apps

### ISSUE THREAD

**Issue by jasonmbrown** [Depressurizer/Depressurizer#189]
When trying to Auto-Categorize games that have no store page, the tags are unable to be obtained.

If steam no longer has the game in the store, or tags were unable to be retrieved for some reason, could we have steamdb as an alternative to at least grab the user tags for a game.

If implemented a new setting could be added to use steamdb as the primary source for the tags with the store being the backup location.

Heres an example game that is no longer on the steam store "Depth Siege Atlantis" and the steamdb link for it [https://steamdb.info/app/849550/info/](https://steamdb.info/app/849550/info/) The 'User Tags' are the last entry on that page. All of the tags use an html class "btn btn-sm btn-outline btn-tag" so it shouldn't be very difficult to parse the text on each link.

**Comment by kekalot** [comment]
I support this, I have hundreds of games with no store pages and I have had to look up a ton of them on Youtube to even know what they are

**Comment by mvegter** [comment]
Hi @jasonmbrown , thanks for your suggestion but the following is the case:
> No, there's a chance you'll get automatically banned for doing so. If you want to be kept up to date on updates for a certain app, use our realtime updates page.
We also do not allow scraping/crawling on SteamDB. Please get the information from Steam itself, for example using SteamKit, the Storefront API, or other various Steam Web APIs.
If you are looking at this for educational and academic purposes, you can email us using your university email with details.

See https://steamdb.info/faq/#can-i-use-auto-refreshing-plugins-or-automatically-scrape-crawl-steamdb for the original

**Comment by mvegter** [comment]
This is part of the [Depressurizer (Premium) API](https://github.com/Depressurizer/Depressurizer#depressurizer-premium-api-), for the normal Depressurizer  using the Steam Store page scraper you will have to manually do this.
