### ISSUE TITLE
Database don't work correct

### ISSUE THREAD

**Issue by freggern** [Depressurizer/Depressurizer#19]
## Expected Behavior
Scraped games correct extract AppInfo.

## Actual Behavior
When I scraped my games 4000+, more then 100+ doesn't show that they have an App Info. But inside the JSON Database the information are their. 
- The issue is that the game is in the database: Here the snipped of the JSON File: https://pastebin.com/fhCjAxLf , but the Database Editor show that the game has no App Info. Think the problem is "LastAppInfoUpdate": 0,`
- When I use "Auto-Categorize" all games without "AppInfo" will removed from their categorize where they are before in, so it destroy my private sorting. (I replace my sharedconfig.vdf...). Maybe their is  a direct refernce to the issue #17

Some of the games have an App Info but doesn't show as scraped.
- An example of a not scraped game with an AppInfo is: https://pastebin.com/VZcXbGsW. But this is not the Problem I think.

## Steps to Reproduce the Problem
1. Scrape a game like ID:8850 - Bioshock Infinitive
2. Use  #"Auto-Categorize"

## Specifications
  - Version:1.4.0
  - Operating System: Win10

**Comment by freggern** [comment]
Look into the problem and it looks like all the games have an age check, when "LastAppInfoUpdate": 0,

I will look into this and try to fix it

**Comment by freggern** [comment]
This fix #21 work for my problem

**Comment by mvegter** [comment]
@freggern Fixed in v2.0.0 [Download Here](https://github.com/mvegter/Depressurizer/releases/tag/v2.0.0)
