### ISSUE TITLE
[REQUEST] Update setting "Ignore - Played on Another Platform"

### ISSUE THREAD

**Issue by ICDeadPpl** [Depressurizer/Depressurizer#193]
It would be handy to be able to hide owned games in the Steam Store.

**Describe the solution you'd like**
Enabling/checking the checkbox "Ignore" - "Played on Another Platform" would hide the game in the store, while still using it for recommendations.

I don't know if this is possible, but it would be nice. Manually doing this would take forever with a big library.

**Comment by mvegter** [comment]
Hi @ICDeadPpl , thanks for your request. I do not see this fit for Depressurizer.
