### ISSUE TITLE
[BUG] Internal server error due to scraping speed

### ISSUE THREAD

**Issue by NeonLightning** [Depressurizer/Depressurizer#194]
when doing a scrape. after about 150-200 it gets an internal server error. if i wait for a couple minutes and try again it works for another bunch
but if i start again right away it'll error right away.

**Comment by lainverse** [comment]
I have the same issue, but now it stops after ~25 scrapes and then goes VERY slow.
Scraping speed is fine for small library updates, but first run on a large library is awful.

**Comment by Tythesly** [comment]
@NeonLightning @lainverse I have found that just having the program Fiddler (either the [Everywhere](https://www.telerik.com/fiddler/fiddler-everywhere) or [Classic](https://www.telerik.com/fiddler/fiddler-classic) version) running will prevent it from producing errors. It scraped over ~~3k~~ 5.1k games without a single error when I did it.

**Comment by mvegter** [comment]
This is part of the [Depressurizer (Premium) API](https://github.com/Depressurizer/Depressurizer#depressurizer-premium-api-), for the normal Depressurizer  using the Steam Store page scraper you will have to manage the batch size yourself.
