### ISSUE TITLE
[BUG] New added Collections not showing up.

### ISSUE THREAD

**Issue by LockMan007** [Depressurizer/Depressurizer#195]
New added Collections not showing up.

Save a new Collection.
attempt to update Depressurizer.
restarting both Steam and Depressurizer don't have any effect.

**Expected behavior**
Update list.

Extra info:
I only got this program, in order to export a list of "Remote Play Together", but since I can't access this new "collection" I added on Steam, I can't do this. I waited some time, tried toggling public/private profile, saved the WebAPI key, made a copy of the collection, saved depressurizer profile and so on. nothing works.

**Comment by NeonLightning** [comment]
depressurizer doesn't work since steam updated their library system sadly. now it seems to be server side.

**Comment by vinanrra** [comment]
Check this @LockMan007 https://github.com/Depressurizer/Depressurizer/issues/178#issuecomment-674452729
