### ISSUE TITLE
[BUG] Not pulling release date when scraping.

### ISSUE THREAD

**Issue by Tythesly** [Depressurizer/Depressurizer#196]
**Describe the bug**
Release date data is not being pulled when scraping game info.

**To Reproduce**
1. Scrape a game.
2. That's it.

**Expected behavior**
I expected it to pull this info so that I can categorize by year it was released.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 21H1 (build 19043.985)
 -  .NET Version: 4.8 (whatever is the latest)

**Comment by mvegter** [comment]
Hi @Tythesly , the `Year` column is populated for me. Could you provide some more information (e.g. screenshots or games/software where you are missing information)?

**Comment by Tythesly** [comment]
It seems to work now. Could it possibly been because of https://github.com/Depressurizer/Depressurizer/issues/198?

**Comment by mvegter** [comment]
> It seems to work now. Could it possibly been because of #198?

It is not impossible but during the scraping of the store page we are also receiving the release date, so at least after scraping it should have appeared.

**Comment by Tythesly** [comment]
Yeah its all good now! Thanks for the help :)
