### ISSUE TITLE
[BUG] Can't pull game list.

### ISSUE THREAD

**Issue by Tythesly** [Depressurizer/Depressurizer#198]
**Describe the bug**
Everytime I try to update the game list I get an error that says There was an error downloading the profile data: The remote server returned an error: (401) Unauthorized.

**To Reproduce**
1. Try to update the game list

**Expected behavior**
I expected it to update my game list.

**Screenshots**
![Screenshot_32](https://user-images.githubusercontent.com/2800945/122086946-33c05100-cdd2-11eb-9bfb-480f21df53df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Version 19043
 -  .NET Version 4.8

**Additional context**
Didnt't have any issues in the past. Maybe steam  updated something :(

**Comment by mvegter** [comment]
Hi @Tythesly , thanks for your report. Could you verify the following:

* Open your File Explorer and go to: `%appdata%/Depressurizer`
* Open the `Default.profile` and find the `<web_key>YOUR_STEAM_WEB_API_KEY</web_key>` entry
* Go to https://steamcommunity.com/dev/apikey and see if that matches with the value of `YOUR_STEAM_WEB_API_KEY`
* Update the  `Default.profile` with the new/correct key

**Comment by Tythesly** [comment]
Perfect! I don't know how it had something different but it works now thanks!
