### ISSUE TITLE
Silently swallowing unknown exceptions is the worst idea ever

### ISSUE THREAD

**Issue by AndrewSav** [Depressurizer/Depressurizer#20]
You do not want to do this:

https://github.com/mvegter/Depressurizer/commit/778c0f32e3186dcc945e94fc5bbee213eb60bf2d#diff-6712656fa031d6ed308bf672c7f67748R64

I understand that you want to log it, but you also have to _terminate_ after you did. Otherwise your program now is inconsistent state, and user is left with unpredictable behavior. Only swallow exceptions you know how to handle, that is you know exactly why they happened.

**Comment by mvegter** [comment]
@AndrewSav Totally agree on that. There are a lot of try-catch in the code without any usefull logging (or just none at all). Thus catching anything at this point is, for me, better then ignoring it. 

Proper logging and error catching is under progress due to being file / class based progress.
