### ISSUE TITLE
[BUG] "Adult Only" Games not getting scrapped

### ISSUE THREAD

**Issue by Tythesly** [Depressurizer/Depressurizer#201]
**Describe the bug**
Games that are marked as adult only are not getting scrapped.

**To Reproduce**
1. Own adult games
2. Try to scrape game info

**Expected behavior**
I expect it to pull game data.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H1
 -  .NET Version 4.8

**Additional context**
I think it has to do with how steam hides adult games unless the exact name for it is searched. Or it could be a age gate thing.

**Comment by mvegter** [comment]
Hi @Tythesly , thanks for your report. Could you provide example games (either name or app id) where you see this happening?

**Comment by Tythesly** [comment]
This issue has been resolved with the release of the premium version!
