### ISSUE TITLE
[BUG] Warning: No game data found.

### ISSUE THREAD

**Issue by keldian** [Depressurizer/Depressurizer#202]
**Describe the bug**
Any attempt to update the game list fails with _Warning: No game data found. Please make sure the custom URL name is spelled correctly._

**To Reproduce**
Create a new profile by selecting from users found on local machine or by entering 64-bit ID.
OR
Load an existing profile
OR
Click _Update Game List_

Possibly related issue: Creating a new profile by manually entering Custom URL (in the format https://steamcommunity.com/id/[myid]/) fails with _Error: Could not find the Steam profile Specified._ 

I also tried deleting the contents of %AppData%\Depressurizer and starting from scratch. Same result.

**Expected behavior**
The game list loads.

**Desktop (please complete the following information):**
 - 4.13.0.0
 - Windows 10 v2004
 - .NET 4.8.04084

**Additional context**
My Steam privacy settings have not changed since the last time Depressurizer successfully loaded the games list, but here they are:

> My basic details:Public
> Your profile name and avatar are visible to anyone who visits your profile and are used to represent you in multiplayer games.
> My profile:Public
> 
> Your community profile includes your profile summary, friends list, badges, Steam Level, showcases, comments, and group membership.
> 
> It also includes the following elements which you can control individually:
> Game details:Public
> This category includes the list of all games on your Steam account, games you’ve wishlisted, your achievements and your playtime. This setting also controls whether you’re seen as "in-game" and the title of the game you are playing.
> [ ] Always keep my total playtime private even if users can see my game details.
> Friends List:Friends Only
> This controls who can see your list of friends on your Steam Community profile.
> Inventory:Public
> Your inventory includes items you've received in games that use Steam Trading. It also includes any Steam Trading Cards you've collected and extra copies or Steam Gifts.
> [ ] Always keep Steam Gifts private even if users can see my inventory.
> Can post comments on my profile:Public
> Screenshots & workshop Items:Per-Item
> Your Screenshots and Workshop Items have privacy settings per-item. Visit an item's page to change its privacy settings.

Also, in reference to [this post](https://github.com/Depressurizer/Depressurizer/issues/123#issuecomment-483508533), the XML data at https://steamcommunity.com/id/[myid]/games?tab=all&xml=1 is visible in a Private window.

**Comment by mvegter** [comment]
Hi @keldian , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.

**Comment by keldian** [comment]
Yeah that fixed it, thanks. That was fast.
