### ISSUE TITLE
[REQUEST] Get tags for pulled games using appinfo.vdf

### ISSUE THREAD

**Issue by jasonmbrown** [Depressurizer/Depressurizer#203]
Unable to scrape games that have no store page, I previously suggested using SteamDB but its against their policy to allow scraping. When I asked them about it they pointed me to this [Steam API utils.appache](https://steam.readthedocs.io/en/latest/api/steam.utils.html#utils-appache)

**Describe the solution you'd like**
Use the appinfo.vdf file to get tagIDs (Would require mapping the tag ID to a tag string) if the store page doesn't exist.

**Describe alternatives you've considered**
Scrape SteamDB (Not allowed per SteamDB policy),
Scrape IGDB (although I don't know how accurate this would be).

**Comment by mvegter** [comment]
This is part of the [Depressurizer (Premium) API](https://github.com/Depressurizer/Depressurizer#depressurizer-premium-api-), for the normal Depressurizer  using the Steam Store page scraper you will have to manually do this.
