### ISSUE TITLE
[BUG]Depressurizer removes categories

### ISSUE THREAD

**Issue by NeonLightning** [Depressurizer/Depressurizer#205]
With the new version of depressurizer 4.13.1.0 instead of doing nothing like the previous one. this one just nuked all my steam categories when i saved profile.

**Comment by mvegter** [comment]
Hi @NeonLightning , thanks for your report. Could you recreate your issue and adhere to the bug report template.

**Comment by NeonLightning** [comment]
had to run
steam://resetcollections
