### ISSUE TITLE
Is it compatible with the new Steam client?

### ISSUE THREAD

**Issue by y0LAs** [Depressurizer/Depressurizer#207]
I tried to autocat my games like I used to do with the old client and the changes appeared on Depressurizer but not on Steam, so I was just wondering if the recent updates implicated that it's now compatible with the new client or if we still got to roll back to the legacy one, as it is not stated anywhere on the software description.

**Comment by mvegter** [comment]
Duplicate, see https://github.com/Depressurizer/Depressurizer/issues/178#issuecomment-674452729
