### ISSUE TITLE
[BUG] Genre not being pulled in new version.

### ISSUE THREAD

**Issue by Tythesly** [Depressurizer/Depressurizer#214]
**Describe the bug**
Before 5.0.0 the genre was being pulled when scraping. But for some reason I cannot get it to work with the new version.

**To Reproduce**
1. Scrape Games

**Expected behavior**
Genres to be populated

**Screenshots**
![Screenshot_38](https://user-images.githubusercontent.com/2800945/123355841-7998ba00-d534-11eb-8b8b-d693c523e2c2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H1
 -  .NET Version 4.8

**Additional context**

**Comment by mvegter** [comment]
Hi @Tythesly , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.
