### ISSUE TITLE
[BUG] Not importing Steam Categories

### ISSUE THREAD

**Issue by Tythesly** [Depressurizer/Depressurizer#215]
**Describe the bug**
Is not importing already created  steam categories.

**To Reproduce**
1. Create a new profile
2. Have it set to import steam categories

**Expected behavior**
I did not expect it to remove my previously made categories.

**Screenshots**
![6](https://user-images.githubusercontent.com/2800945/123426735-c5c61780-d591-11eb-8a79-e6ba0f20c848.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H1
 -  .NET Version 4.8

**Additional context**

**Comment by Tythesly** [comment]
It actually looks like it erased all my categories. The version before premium did import and did not erase.

**Comment by Tythesly** [comment]
@mvegter  I am going to wait until you respond in case you need any additional info. I am okay with it erasing the categories I created (I saved pictures of the important ones and what games were in them).

**Comment by bonifacsolyom** [comment]
Happened to me also with the newest version. I tried going back until 4.12.0 but the categories still weren't imported from steam

**Comment by Tythesly** [comment]
> Happened to me also with the newest version. I tried going back until 4.12.0 but the categories still weren't imported from steam

I think its because it pushed the changes to steam automatically at some point when I setup the new profile.

**Comment by mvegter** [comment]
Hi @Tythesly / @bobobot, thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.

**Comment by Tythesly** [comment]
> Hi @Tythesly / @bobobot, thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.

Unable to check because only the source code is available for download.

**Comment by mvegter** [comment]
> > Hi @Tythesly / @bobobot, thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.
> 
> Unable to check because only the source code is available for download.

Check again :)

**Comment by bonifacsolyom** [comment]
Seems to work for me now, thanks for the quick fix!

**Comment by Tythesly** [comment]
I don't know if it worked because steam is going to reset the collections getting rid of them all xD (which again I am totally fine doing. I prefer depressurizer do to the categorizing anyway). I will let it reset the collections. Create some new ones and re-run depresurrizer and see if it pulls the new ones.

**Comment by Tythesly** [comment]
@mvegter it has only pulled 2 of my categories I created in steam.

What I did was close depressurizer without saving the profile to steam or the program. Went to steam and created 2 categories. I added games to them. I opened depressurizer and it imported the two categories. I went on steam and created 2 more categories and filled them with games but depressurizer will not import those. When I go to reset collections it will only show the first two I made.

**Comment by Tythesly** [comment]
Also when I had the app open in the background it gave me this error out of the blue. Hasn't done it a second time but thought you might want to see it.
[dError_20210625112203.log](https://github.com/Depressurizer/Depressurizer/files/6717339/dError_20210625112203.log)

**Comment by Tythesly** [comment]
Okay yeah I just closed depressurizer saving everything. I reset steam collections and it shows only the 2 I made. I closed steam and re opened it. I created 4 more categories and added games to them. I started Depressurizer and it didn't load anything new. I went to edit profile and checked the Import Steam Categories box and clicked save. It said it loaded everything but the new categories are still missing and if I go to reset my collection (I did not save anything in depressurizer) it says I will only have 2 collections after the reset

**Comment by Tythesly** [comment]
If you want give me instructions on how to make a clean slate test (what should I delete to prepare. Like all my collections, files for depressurizer, etc) for importing categories the first time creating a profile and after using depressurizer and I will give it a shot

**Comment by JackofSpades707** [comment]
Please provide a solution for this, I'd love to be able to use this software

**Comment by mvegter** [comment]
Closing as duplicate of #219
