### ISSUE TITLE
[REQUEST] Indicator showing Premium is active/applied.

### ISSUE THREAD

**Issue by Tythesly** [Depressurizer/Depressurizer#216]
**Is your feature request related to a problem? Please describe.**
No Problems.

**Describe the solution you'd like**
 I would just like some indication after filling in the information that the premium features are active after filling out the settings.

**Describe alternatives you've considered**
Either a bar at the bottom that says "Premium - Not Active" or "Premium - Active". Or maybe some confirmation dialog box that pops up after applying the settings.

**Additional context**

**Comment by mvegter** [comment]
Hi @Tythesly , thanks for your request. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) where this is included.

**Comment by Tythesly** [comment]
I do not see anything that indicates the premium was applied to the application.

**Comment by Tythesly** [comment]
Ahh Nevermind. I see what you did in the code but I just didnt catch the programs title change after applying the settings :)
