### ISSUE TITLE
DLC games not being flagged as DLC properly

### ISSUE THREAD

**Issue by nbusseneau** [Depressurizer/Depressurizer#22]
Hi!

It seems like there was a recent change in how DLC are handled, since they aren't properly detected anymore in the Database Editor when scraping:

![depressurizer_2018-02-13_20-10-27](https://user-images.githubusercontent.com/4659919/36168656-20e5e344-10fa-11e8-9ec7-9a89b3a9c335.png)

As you can see, their `Parent` is unset. Additionally, some of them flagged as `Type: Unknown` instead of `DLC`.

This makes the DLC appear under the `Uncategorized` section, even though they aren't actually displayed in Steam, and thus should be hidden.

This wasn't happening a couple weeks back. Was there a change in the Steam API?

**Comment by mvegter** [comment]
@Skymirrh This is not the fault of Steam. The appinfo parser doesn't read the ParentId and thus missing the relation. This is should be fixed in v2.0.0.

**Comment by nbusseneau** [comment]
Interesting. I'm a bit puzzled: how come it was working beforehand, then?

**Comment by mvegter** [comment]
@Skymirrh It has to do how the VDF files are parsed and then how they are processed before and after scraping.

**Comment by mvegter** [comment]
@Skymirrh Fixed in v2.0.0 [Download Here](https://github.com/mvegter/Depressurizer/releases/tag/v2.0.0)

**Comment by nbusseneau** [comment]
Thanks, gonna check it out! 👍
