### ISSUE TITLE
[BUG] Locating Database Issues

### ISSUE THREAD

**Issue by Tythesly** [Depressurizer/Depressurizer#221]
**Describe the bug**
For some reason it keeps thinking the database is in my system32 folder but its not. When I open the database editor and go to Save As it shows its in the correct folder. However after saving it and closing the editor I get another error!

**To Reproduce**
1. Download Depressurizer
2. Run it like normal.
3. Come back to it another day and start getting issues.

**Expected behavior**
I just want it to work T_T

**Screenshots**
![image](https://user-images.githubusercontent.com/2800945/126017865-545db5a8-4647-4a26-bbd8-ece7d9e2d90e.png)
![image](https://user-images.githubusercontent.com/2800945/126017880-a7e7cd16-9271-46ed-946b-7ed45e1ebb2f.png)
![image](https://user-images.githubusercontent.com/2800945/126017918-a85955fc-89df-4e55-9be5-a99078d0bdc5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H1
 -  .NET Version 4.8

**Additional context**
Please Help

**Comment by mvegter** [comment]
@Tythesly did you recently update Windows by any chance? Seems weird that its doing this all of a sudden.

**Comment by Tythesly** [comment]
Negative. I always keep my computer paused until I stop seeing news on how patches are causing issues xD

**Comment by Tythesly** [comment]
Its happened 2 times so far. I am going to give the new release a try and see if it happens again. OH does it matter if the program is not on the drive windows is installed on? I have it on the drive that steam is installed on.

**Comment by Tythesly** [comment]
Okay it just happened with the latest version. I did everything and closed the app. All my categories are perfect. I open the app today and exact same errors. I really don't want to have to delete every file of this app and redo everything (download, options, premium setup, scrape) every single time I want to use this :'(

Any Ideas.

**Comment by Tythesly** [comment]
@mvegter if you can figure this out I will raise my contribution to $8 a month lol

I just don't know why the first thing it does when you start it makes it pop up that error of it trying to save the database to the system32 folder :/

The only fix I have found is to delete the database.json and redo the scraping... but it will just keep happening even though I save the database file to be in the same folder as the EXE

**Comment by Tythesly** [comment]
@mvegter I figured out the issue. If I run Depressurizer as an administrator the issues are no longer present.
