### ISSUE TITLE
[BUG] Some Games not found in HLTB (HowLongtoBeat)

### ISSUE THREAD

**Issue by jeremybris** [Depressurizer/Depressurizer#222]
**Describe the bug**
Some games are missing from HLTB. So far, I've noticed "Factorio" and "Rimworld".

**To Reproduce**
1. Open "Depressurizer-v5.2.0.exe"
2. Click on "Tools"
3. Click on "Database Editor"
4. Search for "Factorio" or "Rimworld"
5. Double click on the game. A window will pop up, showing the game's stats with missing HLTB stats.

**Expected behavior**
There should be any time in minutes under HowLongtoBeat.com stats, but it is all 0's.

**Screenshots**
| Depressurizer | HowLongtoBeat.com | 
 | ------------- | ------------- | 
| <img width="949" alt="Capture866" src="https://user-images.githubusercontent.com/11889359/126076481-bc971084-499f-4064-a611-cae0eba0404a.PNG"> | <img width="499" alt="Captureby97" src="https://user-images.githubusercontent.com/11889359/126076467-c26f969a-2538-41b5-8813-719302f20821.PNG"> | 
 | <img width="954" alt="Captured856" src="https://user-images.githubusercontent.com/11889359/126076473-53aa24ad-755d-4c96-bf13-ea33b7882e61.PNG"> | <img width="475" alt="Capture251sa" src="https://user-images.githubusercontent.com/11889359/126076500-a052c2f4-2887-4ddf-a7ce-5ef0d8da0a8b.PNG"> | 

**Desktop (please complete the following information):**
 - OS: Windows 10, Latest Version
 -  .NET Version: Latest

**Additional context**
It may be something I'm doing wrong. I'm new to depressurizer.

**Comment by mvegter** [comment]
Hi @jeremybris , this is sadly as expected. Depressurizer actually uses https://www.howlongtobeatsteam.com instead of https://howlongtobeat.com/ . You can improve the data set by logging in and updating any missing links. Another option would be to find another data source / API which can link the HLTB information with Steam Ids

**Comment by jeremybris** [comment]
Oh, I thought [you were saying](https://github.com/Depressurizer/Depressurizer/issues/147#issuecomment-866061098) you closed #147, because depressurizer uses https://howlongtobeat.com times, but I read that wrong. My bad.
