### ISSUE TITLE
[Database] Error Saving & loading database.

### ISSUE THREAD

**Issue by JourneyOver** [Depressurizer/Depressurizer#23]
When trying to save a large scrapped list of games, I seem to always end up running into an error for some reason.

the full error that is thrown is
```
Error saving file: 
Exception of type 'System.OutOfMemoryException' was thrown.
```

No errors in the log or anything, just the above in a popup a few seconds after clicking save database in the database editor. The error isn't thrown when trying to save a small selection of scrapped games.

Steps to reproduce:
1. clean both appdata & local folder of depressurizer
2. open depressurizer and go with all default settings other than choosing my profile
3. open database editor
4. untick"show owned only"
5. Fetch list (fetch list get's canceled for some reason though)
6. Update app info
7. scrape unscraped
8. Wait until you hit at least 5,000+ out of how ever many there after that needs scrapped, or go until you scrape everything
9. Try to save database.
10. error pops up a few seconds after trying to save database
------------------------------------------------------------------------

Another issue

if I save the DB and then exit the database editor the program freezes for a few seconds and then all the tags that where just there for every game is gone again and instead marked as < No Tags > and if I go back into the database editor everything that I had just scraped ends up being marked as unscraped.

so ontop of an issue of running into a save issue, there seems to be a loading database issue as well..

Steps:

1. open database editor
2. Fetch list (fetch list get's canceled for some reason though)
3. Update app info
4. scrape unscraped
5. let it scrap a few items and then stop it
6. save database
7. exit database editor
8. go back into the database editor
9. everything that you just scraped is unscraped again

Neither of these two issues happen when using the latest version from https://github.com/Depressurizer/Depressurizer but seeing as how it's no longer being maintained I'd like to get these two issues fixed in here.

**Comment by mvegter** [comment]
@JourneyOver Could upload your appinfo.vdf file, this is the default location:
> C:\Program Files (x86)\Steam\appcache\appinfo.vdf

(On Github you can't upload *.vdf files. So please rename it to *.vdf.txt)

**Comment by JourneyOver** [comment]
[appinfo.vdf.txt](#removed)

Sure thing, though what I'm doing doesn't pertain to only games I own, I'm trying to scrap unowned as well. I never had this problem when running 0.7.4.2

**Comment by mvegter** [comment]
@JourneyOver How many games do you own?

**Comment by JourneyOver** [comment]
Going by steamDB I own 1,547 at the current time, but like I said I'm trying to scrap unowned (just to have everything in the db) as well which totals out to 56,301 (I did this just fine with 0.7.4.2 without any issues) but using your version it throws the error.

**Comment by mvegter** [comment]
@JourneyOver Could you also upload your packageinfo.vdf (same folder as appinfo)

**Comment by mvegter** [comment]
@JourneyOver And your localconfig.vdf file:
> C:\Program Files (x86)\Steam\userdata\ STEAM3ID \config\localconfig.vdf

**Comment by JourneyOver** [comment]
[packageinfo.vdf.txt](#removed)
[localconfig.vdf.txt](#removed)

**Comment by mvegter** [comment]
@JourneyOver This is fixed in v2.0.0, consider this a beta version:
[Depressurizer-1.9.9-Debug.zip](https://github.com/mvegter/Depressurizer/files/1734729/Depressurizer-1.9.9-Debug.zip)

**Comment by mvegter** [comment]
Open till v2.0.0 is released

**Comment by JourneyOver** [comment]
Will test and let you know how it goes on my end.

**Comment by JourneyOver** [comment]
@mvegter So far looks to be working now without it throwing an error so far :D one thing I do notice though is that when doing a "fetch list" it ends up throwing a "canceled list update" after a few seconds of downloading game list even though I never clicked on cancel. Is "fetch list" just disabled in the 1.9.9 beta you gave me?

**Comment by mvegter** [comment]
@JourneyOver I do not experience this issue. Do you have a private profile? If not, try removing everything in your AppData folder of Depressurizer.

**Comment by JourneyOver** [comment]
@mvegter My profile is public, and I tried that with the same outcome.

Could it be because my list has already been fetched, so instead of it just throwing message about updating 0 things, it just throws a canceled list update?

**Comment by JourneyOver** [comment]
@mvegter so I just ran into the issue again with the whole 

```
Error saving file: 
Exception of type 'System.OutOfMemoryException' was thrown.
```

So I guess this issue actually isn't fixed.

**Comment by mvegter** [comment]
@JourneyOver If you clean both appdata and the local folder of Depressurizer (thus only having the exe) which steps are you taking before you get this issue?

**Comment by JourneyOver** [comment]
@mvegter 

1. clean both appdata & local folder of depressurizer
2. open depressurizer and go with all default settings other than choosing my profile
3. open database editor
4. untick"show owned only"
5. Fetch list (fetch list get's canceled for some reason though as I mentioned above)
6. Update app info
7. scrape unscraped

Those are the main steps I take.

8. Wait until either scrape unscraped is done or stop it when it starts getting into bigger numbers.
9. Try to save database.

those are the last two steps, 8 seems to vary, I haven't found the exact point on when it'll start throwing errors on when saving the DB, but it always seems to be between 5k-10k and above.

**Comment by mvegter** [comment]
@JourneyOver Could you clarify:
>  ... between 5k-10k and above.

What are you refering to?

**Comment by JourneyOver** [comment]
on this thing here https://i.imgur.com/gl8aU4Z.png when it gets between 5-10k and above on the scrapped part of the unscrapped and I stop it or I just let it go until it gets all the way through and then save the Database it's when it throws the error..

it's hard for me to explain it anymore clearer than that..

**Comment by JourneyOver** [comment]
Another thing I notice...

if I save the DB and then exit the database editor the program freezes for a few seconds and then all the tags that where just there for every game is gone again and instead marked as < No Tags > and if I go back into the database editor everything that I had just scraped ends up being marked as unscraped.

so ontop of an issue of running into a save issue, there seems to be a loading database issue as well..

Steps:

1. open database editor
2. Fetch list (fetch list get's canceled for some reason though as I mentioned above)
3. Update app info
4. scrape unscraped
5. let it scrap a few items and then stop it
6. save database
7. exit database editor
8. go back into the database editor
9. everything that you just scraped is unscraped again

**Comment by JourneyOver** [comment]
@mvegter I've changed the name of this issue to better reflect things.

**Comment by mvegter** [comment]
@JourneyOver Fixed in v2.0.0 [Download Here](https://github.com/mvegter/Depressurizer/releases/tag/v2.0.0)

**Comment by JourneyOver** [comment]
@mvegter great, will test it out and see if it works for me or not.

**Comment by JourneyOver** [comment]
@mvegter so far everything looks to be working now on saving/loading the database, one issue I'm still running into though is the fetch list being canceled after a few seconds whenever I try to use it. is it just throwing a cancel instead of throwing a "updated 0 in database" or is this just a bug or something?

**Comment by mvegter** [comment]
@JourneyOver If you are talking about the fetch list in database editor than I'm not able to reproduce your issue.

**Comment by JourneyOver** [comment]
Yes I am talking about the fetch list in the database editor, could it be because the database that you provide with the release is up to date on all the games on steam or something?

**Comment by mvegter** [comment]
@JourneyOver I have tested it both with the provided release as with a clean install.

**Comment by JourneyOver** [comment]
It is strange that you are not able to reproduce the issue, but I am able to reproduce it 100% of the time since I haven't been able to use fetch list at all.

In your 1.4.0 release I am able to use the fetch list just fine without it canceling out, but then of course I run into the whole database not saving/loading, it's just been the 1.9.9 beta you gave me and the 2.0.0 release that the fetch list is broken for me.. It's like the world just doesn't want me to use your releases...

**Comment by mvegter** [comment]
@JourneyOver How many items are mentioned in the statusbar of the database editor after pressing update game list?

**Comment by JourneyOver** [comment]
@mvegter Well now I Just ran into another bug if you mean the "update app info" button 
![](https://user-images.githubusercontent.com/13910285/36685527-3746dfe6-1ae9-11e8-8245-6b5b734711e9.png)


Was running a scrap unscrapped and stopped it and save the database, after the db saved I clicked on "update app info" to get you the item numbers in the status bar and it froze for a few seconds and then threw the above.

**Comment by JourneyOver** [comment]
[depressurizer-(26-02-2018).log](https://github.com/mvegter/Depressurizer/files/1759658/depressurizer-.26-02-2018.log)
This is the log.

**Comment by mvegter** [comment]
@JourneyOver I honestly don't know where the fault lies. I did the exact same steps, yet I don't get the mentioned error.

Also right-under it states 56869 total, I got the same number (at least really close 56800) after a fetch list.

**Comment by JourneyOver** [comment]
There's a ton of errors in the above log that I put up, maybe something in there can help with figuring out the cause?

and I don't know why I am always running into issues with your version always throwing a outofmemeory exception for something at some point...Now I can't even update the app info anymore..

**Comment by JourneyOver** [comment]
@mvegter oof actually here is the full log, for some reason it didn't output a full log until I closed Depressurizer

[depressurizer-(26-02-2018).log](https://github.com/mvegter/Depressurizer/files/1759682/depressurizer-.26-02-2018.log)

**Comment by JourneyOver** [comment]
@mvegter so a realization that I just noticed! even though the "fetch list" is getting canceled it still seems to update the actual app list, I went and deleted the log and re-opened up depressurizer and just went to do a fetch list and noticed the number in the status bar go up a little bit so then closed depressurizer after saving the database and all that and went to look at the log and it ends up showing

```
02/26/2018 11:53:51 Info    | Downloading Steam app list
02/26/2018 11:53:52 Info    | XML App list downloaded
02/26/2018 11:53:52 Info    | Loaded 3 new items from the app list.
```

SO I guess I just have to live with it saying "fetch canceled" instead of how ever many things got updated at the time in the status bar..

As for the OutOfMemeoryException, we need to get that fixed now otherwise I can't ever run a "update app info" now..

**Comment by mvegter** [comment]
@JourneyOver You can enable (believe it is default true) in options to update from appinfo on start. Checking if there might be a wrong localized string somewhere.

**Comment by mvegter** [comment]
@JourneyOver The FetchDialog never increased the finished jobs, thus it would always be Canceled or Stopped as it wasn't equal or higher than the TotalJobs (Must be set to 1 else there would be a zero-divison).

**Comment by JourneyOver** [comment]
@mvegter so that is the reason on why it goes and throws a canceled for me even if it did fetch new things?

And yea I know have the app info on start currently enabled, but needs to be looked into regardless I think so it could get fixed so no one else runs into the problem.

**Comment by mvegter** [comment]
@JourneyOver That is correct. CompletedJobs was never increased and thus always lower than TotalJobs.

```csharp
if (CompletedJobs >= TotalJobs)
{
	DialogResult = DialogResult.OK;
}
else if (Canceled)
{
	DialogResult = DialogResult.Cancel;
}
else
{
	DialogResult = DialogResult.Abort;
}
```

I have removed JSON caching of appinfo (in the appdata folder) as that seems to be the issue for you. I haven't experienced this issue nor was I able to reproduce them from your info.

**Comment by JourneyOver** [comment]
@mvegter ah gotcha, well glad we got that figured out :D and hopefully you removing the json caching will fix the issue on the appinfo memory exception, this one doesn't seem to be reproducable 100% of the time (or at least from what I can tell anyways) unlike the whole saving to database memory exception that I was having before.

**Comment by mvegter** [comment]
@JourneyOver Please do a clean install:
- Delete the appdata folder of Depressurizer (WIN + R -> %appdata%)
- Remove existing executable and database (removing readme is optional)

Then try this one [Depressurizer v2.1.0](https://github.com/mvegter/Depressurizer/releases/tag/v2.1.0).

**Comment by JourneyOver** [comment]
@mvegter fetch list looks to be good now, no more "fetch list canceled" message unless I cancel it myself. Will get back to you on the memory exception here in a bit.

**Comment by JourneyOver** [comment]
@mvegter haven't been able to produce a memory exception yet so looks like it's all fixed now :D if I run into anything new I will let ya know but I'll create a new issue for whatever it is instead of just commenting on this closed one!
