### ISSUE TITLE
Steam not reflecting changed collections

### ISSUE THREAD

**Issue by slcc2c** [Depressurizer/Depressurizer#231]
On 5.2 steam is no longer reflecting saved changes.

**Comment by mvegter** [comment]
Duplicate of #219

**Comment by slcc2c** [comment]
> Duplicate of #219 

I am having a different issue than reported in #219. Everything appears fine in the UI but nothing saves to steam. I have used the tools for years but recently moved to 5.*.

**Comment by slcc2c** [comment]
@mvegter hey if you wouldn't mind hearing me out, this is a different issue than the bug that you linked. What other documentation or explanation do you need?
