### ISSUE TITLE
More Language Support

### ISSUE THREAD

**Issue by tony199555** [Depressurizer/Depressurizer#25]
Hi, thanks for your work. It is really cool that this program is still actively maintain. I would love to see Simplified Chinese as one of the options. I love the automation but I still have to do some manual modification because I want the full list is in Sim. Chinese.

As much as I do not know C#, I will do my best if you need help.

**Comment by mvegter** [comment]
@tony199555 Could you clarify this:
> manual modification because I want the full list

What do you mean with "full list"? The Depressurizer interface or the categories / tags / flags ..

**Comment by tony199555** [comment]
@mvegter Sorry, I should be more clear. I mean I want to have the cat./tags/flags in Sim. Chinese so I don't have to change it every time I sort. In current version, it will auto cat. into a category that has a English name. It auto cat. then I need to copy all of the game in one cat. to another cat. that correspond with a Chinese name. Hope I have clarified enough.

**Comment by mvegter** [comment]
@tony199555 This should be fixed in the next release.

**Comment by mvegter** [comment]
@tony199555 [Depressurizer v2.2.0](https://github.com/mvegter/Depressurizer/releases/tag/v2.2.0).

**Comment by tony199555** [comment]
Thank you!
