### ISSUE TITLE
Devs/Publishers Autocat is broken

### ISSUE THREAD

**Issue by ppriest** [Depressurizer/Depressurizer#27]
This was originally added at my request.

The Developers pane doesn't populate with anything for me (maybe because over 1000 distinct developers?)

Clicking 'Rebuild List' is unstable - the results change each time slightly. Counts go up and down for a given publisher.

Also, sometimes, particularly if the game count is set to 0, it just freezes when you click 'Rebuild List' and you need to close the dialog.

**Comment by mvegter** [comment]
@ppriest This should be fixed in the next release.

**Comment by mvegter** [comment]
@ppriest [Depressurizer v2.2.0](https://github.com/mvegter/Depressurizer/releases/tag/v2.2.0).
