### ISSUE TITLE
Add the version number to future release zips

### ISSUE THREAD

**Issue by alshain** [Depressurizer/Depressurizer#32]
Currently, all ZIPs are named "Depressurizer.zip". I think it would be better if the version name was contained in the file's name, e.g. "Depressurizer 2.3.0.zip"

**Comment by mvegter** [comment]
@alshain I can agree on that. I'm going to leave this open till the next release.

**Comment by mvegter** [comment]
@alshain See the latest release [v2.4.0](https://github.com/mvegter/Depressurizer/releases/tag/v2.4.0).
