### ISSUE TITLE
Filters Not Being Persisted

### ISSUE THREAD

**Issue by richardfrost** [Depressurizer/Depressurizer#33]
## Expected Behavior
When I create filters I can use them until I close the application, then when I launch it again all my filters are missing. This used to work and I'm not sure when it stopped.

## Actual Behavior
Be able to create custom filters and save them, and have them persist between application launches. I completely emptied out my application folder and the `AppData` to try and make sure it wasn't something I did, but the issue is still present for me. Any thoughts?

## Steps to Reproduce the Problem
  1. Turn on "Advanced Filter"
  2. right-click on an entry in the left-hand pane and add it to the filter
  3. Click the save button and enter a name.
  4. Turn off the "Advanced Filter" and then turn it on again to see your filter in the dropdown.
  5. Close the application and re-launch it, and the filter dropdown will be empty.

## Specifications
  - Version:
    - 2.3.0
  - Platform:
    - Windows 10

**Comment by richardfrost** [comment]
Its entirely possible I'm just doing something wrong, but like I said I have tried it from a clean slate and still had the issue, so I'd love to see if others see this same behavior or not.

**Comment by mvegter** [comment]
@richardfrost I can confirm this issue, currently working on a fix.

**Comment by richardfrost** [comment]
Awesome, thanks! :)

**Comment by mvegter** [comment]
@richardfrost This should be fixed in the latest release [v2.4.0](https://github.com/mvegter/Depressurizer/releases/tag/v2.4.0).

**Comment by richardfrost** [comment]
Confirmed its working correctly for me now. Thanks so much for fixing this!
