### ISSUE TITLE
Visit store page

### ISSUE THREAD

**Issue by LonerD** [Depressurizer/Depressurizer#35]
For saving changes Steam client must be closed.
But after pressing "Visit store page" Steam client opens.
Please return (or add as another option) previous behavior - Visit store page in default browser.

**Comment by mvegter** [comment]
@LonerD 
> For saving changes Steam client must be closed.

This is not completely true. You must either close the Steam client or restart the client after saving any changes in Depressurizer to be able to use those changes in the Steam client.

> Please return (or add as another option) previous behavior - Visit store page in default browser.

I will consider adding option for this.
