### ISSUE TITLE
Some games don't properly scrape complete data.

### ISSUE THREAD

**Issue by TheKojukinator** [Depressurizer/Depressurizer#37]
## Expected Behavior
When game data is scraped, the relevant database fields are populated with what is visible on the game's store page. For ex: genre, tags, user scores.

## Actual Behavior
For some games, the scrapes are incomplete. I've noticed this so far for the following games:
- Alien Isolation - https://store.steampowered.com/app/214490/Alien_Isolation/
![image](https://user-images.githubusercontent.com/30471780/39335408-e1fd63a4-4980-11e8-9020-786407c23643.png)
![image](https://user-images.githubusercontent.com/30471780/39335420-f5613a4c-4980-11e8-9685-5c2000501ead.png)
- Awesomenauts - https://store.steampowered.com/app/204300/Awesomenauts__the_2D_moba/
![image](https://user-images.githubusercontent.com/30471780/39335442-174e2656-4981-11e8-8db4-912db7cda55d.png)
![image](https://user-images.githubusercontent.com/30471780/39335450-20bc05fa-4981-11e8-9a08-fd76611c431d.png)
- Dark Souls III - https://store.steampowered.com/app/374320/DARK_SOULS_III/
![image](https://user-images.githubusercontent.com/30471780/39335461-2beabd36-4981-11e8-93ae-53a7cffc6f58.png)
![image](https://user-images.githubusercontent.com/30471780/39335468-331e21d8-4981-11e8-9bb7-b9e0cdef396a.png)
- Valkyria Chronicles™ - https://store.steampowered.com/app/294860/Valkyria_Chronicles/
![image](https://user-images.githubusercontent.com/30471780/39335479-3de228ee-4981-11e8-8fc8-fa7391487607.png)
![image](https://user-images.githubusercontent.com/30471780/39335499-4a5bf80c-4981-11e8-9bf7-526ff3e2e4b4.png)

## Steps to Reproduce the Problem
1. Load a Steam profile.
2. Open Database Editor.
3. Find any game mentioned above and Scrape Selected, Update App Info, etc...
4. Edit game to see the fetched data, it's probably missing much of it.

## Specifications
  - Version:
    - 2.4.0
  - Platform:
    - Windows

**Comment by TheKojukinator** [comment]
Going back to version 2.3.0, I noticed that the database.xml is about 500kb larger. Some of the games that are missing data in 2.4.0 appear to have it in 2.3.0.

Here's Alien Isolation:
![image](https://user-images.githubusercontent.com/30471780/39336611-6945808a-4986-11e8-924e-d98a7a3d58fc.png)

However, even in 2.3.0, some games are not pulling all their data. For example...
Bayonetta - https://store.steampowered.com/app/460790/Bayonetta/
![image](https://user-images.githubusercontent.com/30471780/39336666-ac43714e-4986-11e8-9368-6981c1776759.png)
![image](https://user-images.githubusercontent.com/30471780/39336684-c78a7330-4986-11e8-9980-39e39e797306.png)

Based on my observations of how Depressurizer fetches data, some of it always comes from the web. When I tested disabling local data and forcing web scraping of my profile, once I got the proper URL supplied, I was still getting errors. When I checked the log it said that Names can't have '"' in them (the quote character). Double checking my games list XML https://steamcommunity.com/id/the_kojukinator/games/?tab=all&xml=1 shows that Valkyria Chronicles has quotes in the name:
`<![CDATA[
Valkyria Chronicles™ Selveria's Mission "Behind Her Blue Flame"
]]>`

I suspect the scraping mechanism isn't handling characters right in some cases, and is failing on a variety of games, and it's not obvious because the UI doesn't provide feedback on errors, and even the log is fairly brief on details.

Hope this extra info helps.

**Comment by freggern** [comment]
Looks like the crawling of steam game pages doesn't work any more... Maybe steam change the html layout of their store page... Checked this issue with the version 2.3.0 and 2.4.0 of depressurizer...

**Comment by mvegter** [comment]
@TheKojukinator and @freggern Thanks for reporting this issue. Steam recently forced HTTPS on all their store pages, yet the Regular Expression where checking for HTTP. A fix is on its way.

**Comment by mvegter** [comment]
@TheKojukinator and @freggern This should be fixed in the latest release [v2.5.0](https://github.com/mvegter/Depressurizer/releases/tag/v2.5.0).

**Comment by freggern** [comment]
Worked for me ;-). Thx for your great support !
