### ISSUE TITLE
Where is the browser feature?

### ISSUE THREAD

**Issue by klaritan** [Depressurizer/Depressurizer#38]
For people like me, I have thousands of games and I just started using depressurizer to categorize them.
I don't remember all of the games I bought and it has been really useful ever since.

The old depressurizer didn't update new games list so I updated to a maintained fork, but I can't seem to find the option to keep the mobile version of the store on the right side of the panel.

Where can I enable it back?

Thanks.

**Comment by mvegter** [comment]
@klaritan Sorry for the late response, this feature will be restored in the next release.

**Comment by mvegter** [comment]
@klaritan This is restored in the latest release, [Depressurizer v3.0.0](https://github.com/mvegter/Depressurizer/releases/tag/v3.0.0).
