### ISSUE TITLE
Remove unchecked categories on Auto-cat

### ISSUE THREAD

**Issue by Quitch** [Depressurizer/Depressurizer#40]
Auto-categorisation offers a range of checkboxes on how you would like to categorise your library. When Auto-category is run it filters games by the selected boxes, but keeps the existing categorisation structure.

I would like to see the tool remove the categories which are no longer checked for games it is categorising. For example, on the first run you check all boxes and categorise all games. You now see that YEAR is not useful, so you uncheck that and re-categorise all games. The tool removes all the selected games from YEAR categories and automatically deletes the empty ones.

This allows for an easy clean-up through a single button press.

**Comment by mvegter** [comment]
Closing this issue after a prolonged period of inactivity. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
