### ISSUE TITLE
Categorization for VR Support And Language Not Working

### ISSUE THREAD

**Issue by DerekCL** [Depressurizer/Depressurizer#41]
**Is your feature request related to a problem? Please describe.**
Given I'm editing Autocats
When I try to create a new AutoCat List Category for Language or VR
Then nothing happens

**Describe the solution you'd like**
Given I'm editing Autocats
When I try to create a new AutoCat List Category for Language or VR
Then a new category for language or VR is created so I can categorize my games

**Describe alternatives you've considered**
Manual Categorization

**Steps To Reproduce**
1. Start Depressurizer
2. click the edit AutoCats button in the bottom left of the main menu.
3. Click create in the bottom left of of the edit AutoCats menu.
4. Select the type to be either Language or VR Support.
5. Give a name (it can be anything)
6. Click Create

**Additional context**
Software Version: v2.5.0
Platform: Windows 10.

**Comment by mvegter** [comment]
@DerekCL Thanks for reporting this issue. I'm currently working on a solution for this.

**Comment by mvegter** [comment]
@DerekCL This should be fixed the latest release, [Depressurizer v3.0.0](https://github.com/mvegter/Depressurizer/releases/tag/v3.0.0). Can you confirm this?

**Comment by DerekCL** [comment]
Looks like the issue has been resolved. Initially my entire interface loaded in German but then i deleted my old profile and everything works. Its possible the new update may cause issues for existing users but for first time setup everything appears to be working.

**Comment by DerekCL** [comment]
also 8/8 description for the change log "A lot".

**Comment by mvegter** [comment]
@DerekCL The language change is correct, the order of the enums has changed but they didn't have a hard-coded value. 

As for the description. I reworked all my changes in the dev-branch to the last version of Theo's Depressurizer.
