### ISSUE TITLE
[Master branch] Developer and publisher scrape can fail

### ISSUE THREAD

**Issue by j-oliveras** [Depressurizer/Depressurizer#45]
**Describe the bug**
I'm using master branch. Into database editor, current regex to scrape developer and/or publisher can fail because both of them can be a curator page link.

**To Reproduce**
1. Open database editor.
2. Scrap `ULTIMATE ARENA SHOWDOWN` (id 757160) or `VA-11 Hall-A: Cyberpunk Bartender Action` (id 447530)
3. Only publisher are scraped.

**Expected behavior**
Developer and publisher are scraped.

**Additional context**
I'm using the master branch compiled be myself without changes.

The regex are:
https://github.com/mvegter/Depressurizer/blob/0fef1b982e5622d13ad0fd311da97722a8faac22/src/Depressurizer/Models/DatabaseEntry.cs#L44
https://github.com/mvegter/Depressurizer/blob/0fef1b982e5622d13ad0fd311da97722a8faac22/src/Depressurizer/Models/DatabaseEntry.cs#L72

**Comment by mvegter** [comment]
@j-oliveras Thanks for reporting. I can confirm this issue, I will be looking into it.

**Comment by azumukupoe** [comment]
I think it's fixed in the latest version, thanks.
Never mind, the bug still exists.
It's gotten better.

**Comment by mvegter** [comment]
Closing this issue after a prolonged period of inactivity. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
