### ISSUE TITLE
[Request] See playtime

### ISSUE THREAD

**Issue by Njbud13** [Depressurizer/Depressurizer#46]
(Moved this from the now dead depressurizer feature requests)

It would be really nice if I could see the current playtime of games (as you can on http://www.lorenzostanco.com/lab/steam/). This to easier find games I have yet not tested in my categories to add a "todo tag" to.

'playtime_forever' seems to be accessible via this api https://developer.valvesoftware.com/wiki/Steam_Web_API#GetOwnedGames_.28v0001.29

http://steamcommunity.com/id/{id here}/games?tab=all&xml=1 which is used in XML web profile updates already contains a field for playtime (<hoursLast2Weeks> and <hoursOnRecord>)

Someone started work on this here:
https://github.com/ErikDavison/Depressurizer/commit/7a03ae09e563db767caf4204bd9fdf5124a65f62

Thanks!

**Comment by mvegter** [comment]
@Njbud13 This will be added in the next release!
