### ISSUE TITLE
upgraded to v3, app no longer in english

### ISSUE THREAD

**Issue by boneskull** [Depressurizer/Depressurizer#47]
**Describe the bug**
The app is no longer in English, which is my OS's language.

**To Reproduce**
Download release `.zip`.  Extract archive and execute program.

**Expected behavior**
Depressurizer would still be in English.

**Screenshots**
![image](https://user-images.githubusercontent.com/924465/42253964-2cce7712-7ef9-11e8-9a99-b66502957211.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: 3.0.0

**Comment by klaritan** [comment]
Can confirm the same issue.

**Comment by mvegter** [comment]
@boneskull and @klaritan try removing your settings file (in de appdata folder -> Depressurizer).

**Comment by mt025** [comment]
Same issue. Deleting settings.json in `%appdata%\Depressurizer\` worked. or changing `"InterfaceLanguage":0` to `"InterfaceLanguage":1` also worked.
