### ISSUE TITLE
Category check boxes always display in Dutch

### ISSUE THREAD

**Issue by Quitch** [Depressurizer/Depressurizer#50]
**Describe the bug**
Regardless of selected language, in version 3.0 the category checkboxes will display in Dutch

**To Reproduce**
1. Download v3.0
2. Run v3.0
3. Change language from Nederlands to English

**Expected behavior**
All text switches from Dutch to English

**Screenshots**
![dutchcategories](https://user-images.githubusercontent.com/5182715/42313673-31b81786-803b-11e8-81fa-2df6f49d277f.png)

**Desktop (please complete the following information):**
 - Microsoft Windows [Version 10.0.17134.112] Pro x64
 - Google Chrome
 - Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by pix0wl** [comment]
Hi, there is already an related issue with a solution (#47). 
Did you tried it?

**Comment by Quitch** [comment]
It did, yes.
