### ISSUE TITLE
Use SteamDB's data for removed and region locked games?

### ISSUE THREAD

**Issue by azumukupoe** [Depressurizer/Depressurizer#52]
**Is your feature request related to a problem? Please describe.**
I want removed or region locked games to be auto-categorized as well.
**Describe the solution you'd like**
Is it possible to use SteamDB's genere and tag data?
**Describe alternatives you've considered**

**Additional context**

**Comment by mvegter** [comment]
@azumukupoe Possible, but impossible at the same time:
> https://steamdb.info/faq/#can-i-use-auto-refreshing-plugins-or-automatically-scrape-crawl-steamdb
