### ISSUE TITLE
New Sentry SDK

### ISSUE THREAD

**Issue by bruno-garcia** [Depressurizer/Depressurizer#54]
I'm at developer at Sentry and I noticed you are working with our latest stable SDK.
I'd like to link you to our [new .NET SDK[(https://github.com/getsentry/sentry-dotnet/) which we have been working for a couple of months now.

Please take into consideration it's only a preview version.
It is much easier to add new features and fix bugs now before the first major version.

The target framework in `netstandard2.0` so compatible with the minimal .NET Framework version you current require (4.6.2). In fact, we run unit tests on .NET 4.6.2.

I'd be happy to submit a PR to add it to your project.

**Comment by mvegter** [comment]
It took a while, but I have updated it to use the latest SDK.
