### ISSUE TITLE
Not loading new games

### ISSUE THREAD

**Issue by DaMarine** [Depressurizer/Depressurizer#57]
Depressurizer is not loading any games newer than 30/07/2017. Attempted with several versions of Depressurizer, including the latest 3.0.0 release. .NET framework is up-to-date and running the latest required version. 

Forcing it to try and load from Steams servers rather than a local copy returns the error 'No game data found. Please make sure the custom URL name is spelled correctly. I've attempted this with the select local user, 64-bit steam ID, and custom URL name, all of which have failed with the same error.

**Comment by mvegter** [comment]
Have you tried removing all files related to Depressurizer?

* The folder where you extracted Depressurizer
* The Depressurizer appdata folder

**Comment by mvegter** [comment]
@DaMarine Could you check if this still happens with the [latest release](https://github.com/mvegter/Depressurizer/releases).

**Comment by DaMarine** [comment]
My bad, I should have updated this sooner. Turned out to be a very broken
Steam installation issue, a reinstall fixed it immediately. Thanks for your
help!
