### ISSUE TITLE
An error occurred while updating the game list:    After parsing a value an unexpected character was encountered: a. Path 'applist.apps[7618].name', line 1, position 412396.

### ISSUE THREAD

**Issue by azumukupoe** [Depressurizer/Depressurizer#59]
**Describe the bug**

**To Reproduce**
1. Go to 'Database Editor'
2. Click on 'Fetch list'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mvegter** [comment]
@azumukupoe I'm not able to re-produce your issue. AppId 7618 belongs to "Railroad Tycoon 3", which is added to my database after clicking on "Fetch List" and is updated after scraping the unscraped.

Could you try a clean install of Depressurizer:
- Deleting the database.json and Depressurizer.exe
- Deleting the appdata folder of Depressurizer

**Comment by azumukupoe** [comment]
I still get the error. Does it have to do with where I live?

2018年8月23日(木) 23:13 Martijn Vegter <notifications@github.com>:

**Comment by mvegter** [comment]
Closing this as it hasn't occurred ever since.

**Comment by u47ska** [comment]
![1](https://user-images.githubusercontent.com/16728590/50956660-39295b00-14f7-11e9-8105-3e51d799379d.PNG)
Encountered a similar error
Clean install of Depressurizer V4.7.0.0
