### ISSUE TITLE
Dutch Language set default

### ISSUE THREAD

**Issue by junnae** [Depressurizer/Depressurizer#61]
**Describe the bug**
I just upgraded to the newest version, 3.10. When i started the program, the language in the profile tool window was in dutch (I think it is?)(I haven't used this or any other program in dutch before, not windows either).
I changed language to english in the options, but in the down left corner it still says 'Bij Genre' 'Bij jaar' etc.

**To Reproduce**
1.Install newest version
2. Open Program

**Expected behavior**
Everything in english by default, and totally english after setting interface language

**Screenshots**

![image](https://user-images.githubusercontent.com/10945642/44743617-48d57380-ab03-11e8-890c-3f01a7101aeb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 10.0.17134 Build 17134

**Comment by mvegter** [comment]
Closing this as a duplicate. Please check the previous issues before creating a new one.
