### ISSUE TITLE
[Request] Language options (Program in Dutch, I only speak English.)

### ISSUE THREAD

**Issue by Fevix** [Depressurizer/Depressurizer#62]
**Is your feature request related to a problem? Please describe.**
I downloaded the program and it's in Dutch. I do not speak Dutch and therefore cannot understand anything in the program. Parts of the UI are in Dutch, and parts are in English. https://gyazo.com/2deaf8718a27417bf670a872dbfc19f9

**Describe the solution you'd like**
Add a dropdown with the Language Icon (http://www.languageicon.org/) next to it for the user to select their language.

**Comment by Fevix** [comment]
At first I thought I found the options, but now I see it's incomplete. 

The bottom left corner remains untranslated even with the program set to English. 

https://gyazo.com/5cce4cb4f8eb9e4ea588be81bbfeb078

**Comment by Zhuinden** [comment]
I have encountered the same problem, 2.5.0 was English, but 3.1.0 is Dutch for some reason.

**Comment by syaifulnizamyahya** [comment]
Same here. I dont know what language is there. I also dont know how to change the language to english.

**Comment by Zhuinden** [comment]
What's even more inconvenient is that it even changed the auto-categories to Dutch. 

I had to manually make them English again.

**Comment by mvegter** [comment]
Everything has been reverted to the original configuration. I suggest you either delete your config file or edit the language to 0 (English).

Sorry for the inconvenience.
