### ISSUE TITLE
[Request] Allow editing the AppId of non-Steam shortcuts (that have steam pages).

### ISSUE THREAD

**Issue by VioletSkies19** [Depressurizer/Depressurizer#63]
Adding non-steam shortcuts that have a steam page (games bought from gog or DRM free releases of games) doesn't allow them to use the steam page's flags/tags/genres/rating etc.

This could be fixed by allowing editing of the game id when using "edit game"

Currently what i am trying to do can be accomplished by going into the default.profile with a text editor and manually changing the id to the id of the steam page, then running autocats on the game then going back into the default.profile and changing the id back to its original negative number id so steam recognizes it. 

Would be nice to have an easier way to do this, even if the ids still have to be manually changed in program. A second idea would be adding a separate input for getting info on non steam shortcuts.

**Comment by git-steve-git** [comment]
Bump for this idea.  I have a fair number f games from GOG (yay DRM-free) but I still use Steam as my central library program.  It'd be awesome if Depressurizer could identify non-Steam games that also happen to exist on Steam - either automagically or by allowing me to input the ID, as suggested - and scrape them accordingly.


(Thanks for the manual workaround, BTW!)

**Comment by mvegter** [comment]
Should be fixed in the latest release!

**Comment by SkyNinja** [comment]
Any explanation for how this works? I've been digging through the UI on and off since the release of 4.10.0, and still haven't figured it out.
