### ISSUE TITLE
[BUG] Category order does not match Steam's order.

### ISSUE THREAD

**Issue by Blayr** [Depressurizer/Depressurizer#65]
In Depressurizer, the "_" character appears before alphabetical characters, in Steam it appears after. Making the sort order match Steam's helps those who like to re-order the categories by prefixing category names with special characters.

**Comment by mvegter** [comment]
@Blayr and @haboutnnah this will be fixed in the next release!

**Comment by Blayr** [comment]
@mvegter 

Awesome! :)
