### ISSUE TITLE
Solved! Review scores missing

### ISSUE THREAD

**Issue by ausghostdog** [Depressurizer/Depressurizer#67]
Never mind, looks like I had to select the tag on the bottom left, then select auto-categorize and it then scraped the missing data

![image](https://user-images.githubusercontent.com/7588602/45922607-ef027680-bf13-11e8-8ebe-7995da0eb595.png)
![image](https://user-images.githubusercontent.com/7588602/45922608-004b8300-bf14-11e8-850f-cfe4f0c04498.png)

As the image shows, a large portion of my games are missing the user reviews

**Comment by Qubits01** [comment]
Hi, I have the same issue but scraping did not do the trick for me.
Over 50% of my games are without review score even though many do have 100s of reviews.
Any ideas on how to fix?
Edit: Also, steam has 324 of my game auto-categorized as VR. Depressurizer only lists 200.

**Comment by ausghostdog** [comment]
@Qubits01 
After playing around I solved mine by selecting the tag first then selecting auto-categorize and it then updated the list 
![image](https://user-images.githubusercontent.com/7588602/45924037-e07a8600-bf38-11e8-9a1a-2d844d147ea7.png)

**Comment by Qubits01** [comment]
I did that but the update is incomplete. It did not load data from all games even though it counted through all of them. I'll open another thread, because it's a different issue

**Comment by mvegter** [comment]
Closing this as @ausghostdog has found a solution and @Qubits01 opened his/her own issue #68 .
