### ISSUE TITLE
No info about games is scraped

### ISSUE THREAD

**Issue by sukhmel** [Depressurizer/Depressurizer#69]
I have installed v.4.0.0 of Depressuriser to a new machine, now I can see a list of games, but no info gets scraped.

In DB editor all the games are marked `scraped` manual rerun does not add info.

HLTB info is loaded.

Edit: when I open in-app browser, it shows empty list of popular tags, but publication year is seen, although also is not scraped.

**Comment by sukhmel** [comment]
So this appears to be a duplicate of #68, as I first thought that one is only for some games not scraping, but there is a person with a same problem as mine.

**Comment by mvegter** [comment]
Closing as duplicate of #68
