### ISSUE TITLE
Different amount of games shown in list when using last and previous versions of app

### ISSUE THREAD

**Issue by sukhmel** [Depressurizer/Depressurizer#70]
When using latest release (v.4.0.0) I get 89 games under `Uncategorized`, when using previous release (v.3.1.0) there are 91 games.

Total count of games also differ (773 shown vs 883 shown in DB editor statusbar).

**Comment by azumukupoe** [comment]
Roughly one third of games on my account are not loaded...

**Comment by mvegter** [comment]
@all, this has to do with the repository transfer to the Depressurizer organization page. Currently working on fix everything.

**Comment by Parsnip** [comment]
Is this why I'm missing 300+ games in Depressurizer? I looked at some of the older bugs and it almost looks like the bug #17 is back.

**Comment by MubarakHAlketbi** [comment]
> Is this why I'm missing 300+ games in Depressurizer? I looked at some of the older bugs and it almost looks like the bug #17 is back.

i think so, i have as well around 300 games not showing up.

**Comment by peloxi** [comment]
a lot of games are missing in DB for example Borderlands 2 (ID: 49520) is missing https://steamdb.info/app/49520/

**Comment by mvegter** [comment]
Closing this issue. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
