### ISSUE TITLE
[REQUEST] sort by if currently downloaded

### ISSUE THREAD

**Issue by Momongaka** [Depressurizer/Depressurizer#72]
When I am not playing a game anymore I uninstall it. Is it possible to add a category for games that are downloaded. This would make it easier to navigate to games I play daily. If not no problem just though it would be very useful when you have a large library.

**Comment by Sleazus** [comment]
Really? You haven't noticed if you go to the LIBRARY shortcut at the top of steam, the one you hover over and it has A BUNCH OF MENUS, ONE OF WHICH IS INSTALLED?

THERE YOU WILL FIND (SURPRISE) ALL THE GAMES YOU HAVE CURRENTLY INSTALLED!!! (SHOCKING I KNOW)

THESE WILL BE CATEGORISED WITH, YOU MAY HAVE GUESSED, ALL THE CATEGORIES YOU'VE MADE WITH DEPRESSURIZER.

PLEASE STOP WASTING PEOPLES VALUABLE TIME

**Comment by Momongaka** [comment]
For one your comments tone was unnecessary, you do not have to respond like an ass to get a point across. It is simple enough to just reply without all the sarcasm. The only person who has wasted time has been you, when you decided to put in the extra effort of being an ass. In the future it may help you to be more polite. Who knows maybe someone you react to in this fashion may be your boss in the future. All in all good luck and I truly hope you mature.

**Comment by Sleazus** [comment]
I apologize for my tone, I was having a bad day. In the future I'll endeavour to just be informative in the future.
It was im,polite and improper and I had no business or right to treat you like that.

**Comment by Momongaka** [comment]
Thank you and apology accepted. I appreciate you telling me about that tab thought. I could not find it before and well now I know! I also hope you feel better I know what you mean I have been having a splitting headache most of this week.
