### ISSUE TITLE
Unknown Review Score

### ISSUE THREAD

**Issue by peloxi** [Depressurizer/Depressurizer#73]
1370 games
1366 Unknown Review Score
4 Review Score

Windows 10
Depressurizer 4.1

I updated today depressurizer and database games. Other autoCATS work good but no info SCORE CAT (and 513 unknown year)

**Comment by Qubits01** [comment]
Exactly the same problem. Fetching info works for the most part. But almost no review scores and #of Reviews are fetched. This is critical to me since I want to do the filtering mostly based on that.

Hint: Missing year might be due to games that were removed from steam.

**Comment by kazerniel** [comment]
I have an overlapping issue, today I updated to 4.2 and Steam-based autocats stopped working alotgether (this includes year, review score and tags). Only HLTB works. I tried switching back to previous Depressurizer versions, but the scraping doesn't work in either of them any more.

Also after the update my Depressurizer was in Spanish for some reason (neither my OS or my Steam profile is in that language), but I managed to find the option to set it back to English.

**Comment by dama-de** [comment]
This seems to be fixed by setting the Steam store language to English in the Depressurizer settings.

**Comment by peloxi** [comment]
> 
> 
> This seems to be fixed by setting the Steam store language to English in the Depressurizer settings.

Solved thank you!

**Comment by Etznab86** [comment]
I'm afraid the problem persists for me. I've changed the store language to english and manually updated the Database. I still don't get User Scores for 90% of my (mostly very common) games (that absolutely still have store pages).

**Comment by bimzcy** [comment]
Still hope Review Score could be display correctly for Non-English language, please fix the bug.

**Comment by mvegter** [comment]
Closing this issue. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
