### ISSUE TITLE
[REQUEST] AutoCat for player count for couch games.

### ISSUE THREAD

**Issue by freggern** [Depressurizer/Depressurizer#74]
Hey,
I would like to see that you can sort games by max player count of couch games...

I created the website https://www.local-games.info. The site collect the players count of couch games on steam. You can easy use this API to get the max. players count and the steamid of games: https://www.local-games.info/api.php

**Comment by mvegter** [comment]
@freggern as you developed the website you might want to give a shot at C# and implement this yourself. Question about the API: Is it open-source and how often do you (and how) update it?
