### ISSUE TITLE
Do not export "uncategorized"

### ISSUE THREAD

**Issue by MrUnbecoming** [Depressurizer/Depressurizer#76]
When exporting the categories, it also exports the "uncategorized" one. I decided I wanted to stop using Depressurizer and just use Steam's category system. After I tried to remove all the categories, it still kept "uncategorized" and I don't know how to get rid of it. Not sure if the functionality to do that is already there, or if it needs to be added to not export the uncategorized games.

**Comment by MrUnbecoming** [comment]
well I figured out to just delete the sharedconfig.vdf. But I still think this is a useful feature. I think instead of exporting the uncategorized games into "uncategorized", just put them into steam's own "games" category if that's possible.

**Comment by mvegter** [comment]
I don't have this category in the regular list of my library (and i have ~80 games uncategorized), I do find this category in the drop down list but I believe this is from Steam as this list doesn't have the "games" category.
