### ISSUE TITLE
4.1.0 - tags list is empty and will not populate

### ISSUE THREAD

**Issue by mendhak** [Depressurizer/Depressurizer#78]
**Describe the bug**
In a clean install of Windows 10 and Depressurizer **4.1.0**, the Edit Autocats dialog doesn't contain any tags, it's empty. I keep clicking Rebuild but the tags list is empty. 

This might be related:  when starting Depressurizer for the first time, this error dialog appears. 

> Error loading game database. Local category and DLC data will not be available.
> Database file does not exist.

In the log file I see this error line just after loading sharedconfig.vdf:

> ERR: Error opening Steam config file: System.IO.FileNotFoundException: Could not find file 'c:\program files (x86)\steam\userdata\23904332\config\shortcuts.vdf'.

I then installed Depressurizer **3.1.0** and the tags list appears fine, there aren't any error dialogs. 

**To Reproduce**
Remove your `C:\Users\<username>\AppData\Roaming\Depressurizer` - (clean install)
Download and unzip the 4.1.0 release. 
Double click Depressurizer.exe
Alert dialog appears

Go to Profile > Edit Autocats...
Click Tags
Tags box is empty
Click rebuild
No tags appear

**Expected behavior**
No alert dialog
Tags appear in Edit Autocats. 

**Screenshots**
![image](https://user-images.githubusercontent.com/746276/47179618-6b6f5600-d316-11e8-9eae-55e4733b18ad.png)

![image](https://user-images.githubusercontent.com/746276/47180469-8fcc3200-d318-11e8-9b50-6187b59ae384.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v1803
 -  .NET Version 4.7.2

**Comment by Turekson** [comment]
I have the same issue with the the tags not showing, but my game database loads up (local sync) all right. I can't even see the tags in the browser view. 

![despressurizer-not-tags](https://user-images.githubusercontent.com/44347311/47271795-5cdaa600-d585-11e8-83fa-67be5a312b86.png)

**Comment by mvegter** [comment]
Closing this issue after a prolonged period of inactivity. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
