### ISSUE TITLE
[REQUEST] Add option to use SteamDB rating formula for UserScore Auto-Cat

### ISSUE THREAD

**Issue by Dark-talon** [Depressurizer/Depressurizer#79]
Hello, I love the program, thank you for the effort and time you have put into this project over the years.
Having the Wilson score option is awesome, and it would also be awesome if we could use the formula that SteamDB now uses, here is an article talking about it. Thank you!

https://steamdb.info/blog/steamdb-rating/

**Comment by Qubits01** [comment]
I like that idea very much but there are much more basic functionalities that need to be fixed first.

**Comment by mvegter** [comment]
@Qubits01 Are there any functionalities that are not (fully) working, if yes please create an issue per functionality so I can look into it.

**Comment by mvegter** [comment]
See https://github.com/Depressurizer/Depressurizer/issues/189#issuecomment-863898602
