### ISSUE TITLE
hi could add dlc

### ISSUE THREAD

**Issue by GrizzlyKt** [Depressurizer/Depressurizer#81]
hi could you add dlc in one of the lists ie genre or flags or tags or can i do it myself thank you for any help

**Comment by mvegter** [comment]
As for as I know DLC's are not shown in the Steam library page, so why would you want DLC's to be shown in Depressurizer?

**Comment by mvegter** [comment]
Closing this issue after a prolonged period of inactivity. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
