### ISSUE TITLE
Won't open profiles

### ISSUE THREAD

**Issue by Mandrake158** [Depressurizer/Depressurizer#85]
Everytime I open the program (or any profile, new or old) I get "Error updating from local files: The given key was not present in the dictionary", it happens whenever I open a profile or if I click on create a new one, thus it redownloads my library list everytime I want to open and change something

I've tried opening the program as admin and giving rights to the Steam folder, but nothing, I'm in the latest version on Windows 10 x64

**Comment by clint229** [comment]
I am getting three errors then the window opens with no games in the list. 
Error updating from local files: Could not find file 'e:\steam\userdata\109xx\config\localconfig.vdf'.

No game data found. Please make sure the custom URL name is spelled correctly.

Error importing steam data list.
Error opening Steam config file:Could not find a part of the path 'e:\steam\userdata\109xx\7\remote\sharedconfig.vdf'.

**Comment by clint229** [comment]
Ok I got it to work. I clicked on Edit Profile. Then I unchecked the boxes for "Update Game list right now" and "Import Categories from Steam right now". I clicked Profile -> Update Game List. and it pulled in my games. I then did Auto-Cat All. Exit Steam and save the Depressurizer profile.

**Comment by mvegter** [comment]
Closing this issue. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
