### ISSUE TITLE
[meta] Chocolatey package created for Depressurizer

### ISSUE THREAD

**Issue by scowalt** [Depressurizer/Depressurizer#86]
I've created a Chocolatey package for Depressurizer. ([what is Chocolatey?](https://chocolatey.org/about))
- Package url: https://chocolatey.org/packages/depressurizer/0.7.1.4
- Package source: https://github.com/scowalt/chocolatey-depressurizer/tree/development

Feel free to review the package and package source and provide feedback! For future releases, also feel free to @ ping me on the pull request / commit. This gives me a notification to update the package manually.

Cheers!

(P.S. Close this issue as you see fit)

**Comment by ibrokemypie** [comment]
@scowalt any chance youre up to doing one for scoop too? prefer scoop to choclatey as it is fully floss and does not have a paywall, totally understand if you dont want to support something you dont use though!

**Comment by scowalt** [comment]
I've never heard of scoop! I created an issue on the chocolatey-depressurizer repo so I don't forget to look into this in the future. https://github.com/scowalt/chocolatey-depressurizer/issues/3

**Comment by Theo47** [comment]
I'll leave this open as a reminder.

**Comment by JourneyOver** [comment]
@scowalt if you are still maintaining this I suggest you update your link to point to the newer repository as this repo is now dead.

new repo is at https://github.com/mvegter/Depressurizer

**Comment by scowalt** [comment]
@JourneyOver thanks for the heads-up! I've opened an issue on my chocolatey package repo to do this: https://github.com/scowalt/chocolatey-packages/issues/16

I have no idea when I'll get around to it.

**Comment by scowalt** [comment]
Closing this out since this repo is inactive and there's a new issue open to move the repo.
