### ISSUE TITLE
Can't install .net 4.7 on W10 2015 LTSB

### ISSUE THREAD

**Issue by IeuanK** [Depressurizer/Depressurizer#9]
My version of Windows 10 is not supported by .net 4.7. This is more an issue in the .net framework (the LTSB is still supported as a major version), but I built Depressurizer using the 4.6.1 and it ran without issues.  
I was instructed on Reddit to make an issue here. There don't seem to be any issues with the current source using .net 4.6.1 on my machine.

## Specifications
  - Version: Current version of source, built in VS2017 targeting .net 4.6.1
  - Operating System: Windows 10 Entprirse 2015 LTSB, build 10240

**Comment by mvegter** [comment]
@IeuanK If I read this correctly you are able to use Depressurizer(Core) if it is build on v4.6.1 or lower?

**Comment by IeuanK** [comment]
Yes, I am able to build the current source with 4.6.1, run it without issues and recategorize my Steam library.

**Comment by mvegter** [comment]
@IeuanK What about v4.6.2?

**Comment by IeuanK** [comment]
Looks like 4.6.2 is fine too

**Comment by mvegter** [comment]
@IeuanK Should be fixed with the latest release [here](https://github.com/mvegter/Depressurizer/releases/tag/v1.0.0).
