### ISSUE TITLE
Category "Purchased by date"

### ISSUE THREAD

**Issue by Vitorrio** [Depressurizer/Depressurizer#94]
Please add the category "Purchased by date"

I have 1300 games, and it's just vital for me in what time period I bought the game.
And yesterday, Steam broke, and deleted all the categories I established.

Here’s how it all might look like:
![idea one](https://user-images.githubusercontent.com/19190915/49916779-82ad6880-fead-11e8-8bb5-e1877fbc42ac.jpg)

AND:
![idea two](https://user-images.githubusercontent.com/19190915/49916538-6957ec80-feac-11e8-9899-869f5effa28b.jpg)

Information on the date of purchase can be obtained from here:
![datafrom](https://user-images.githubusercontent.com/19190915/49916539-6e1ca080-feac-11e8-9b86-9a209b1b1e1a.jpg)

Perhaps in this case, authorization is required within your program.

Since I used the automatic translation tools, I will attach the original text in Russian.

#############################################
Добавьте пожалуйста категории "Куплено по датам"

У меня 1300 игр, и мне просто жизненно важно в какой временной промежуток я покупал игру. 
А вчера, стим поломался, и удалил все установленные мной категории.
Вот как это все может примерно выглядеть:

Информацию о дате покупки можно взять отсюда:

Возможно в этом случае потребуется авторизация внутри вашей программы.

Т.к. я воспользовался инструментов автоматического перевода, если что-то не понятно, приложу оригинал текста на русском языке.

**Comment by mvegter** [comment]
Merging this with #71.
