### ISSUE TITLE
Index out of Range on click in Advanced Filter

### ISSUE THREAD

**Issue by sukhmel** [Depressurizer/Depressurizer#97]
**Describe the bug**
Turned on Advanced Filter mode, clicked on one of the categories so that `checkmark` appeared, got a crash.

**To Reproduce**
1. Click on 'Advanced Filter'
2. Click beside some category to make a mark appear
3. Wait a few seconds

**Expected behavior**
An advanced filter

**Screenshots**
![default](https://user-images.githubusercontent.com/5804169/50003432-a7403800-ffb4-11e8-9a36-907d00469368.png)

**Desktop (please complete the following information):**
 - OS: win 10 home
 - Version 4.5.0
 -  .NET Version 4.0.30319.42000

**Additional context**
I can set advanced filter using right-click context menu for category.

error text:
```
System.ArgumentOutOfRangeException: Exception of type "System.ArgumentOutOfRangeException".
Parameter name: oldState
Actual value was -1.
   in Depressurizer.FormMain.HandleAdvancedCategoryItemActivation(ListViewItem i, Boolean reverse, Boolean updateView)
   in Depressurizer.FormMain.lstCategories_MouseDown(Object sender, MouseEventArgs e)
   in System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   in System.Windows.Forms.ListView.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.ListView.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by git-steve-git** [comment]
I'm having the same issue, but I'm using .NET Framework 4.6.2 (I tried to use the link on your front page to update, but windows said it wouldn't do the update because it was already installed.)

**Comment by mvegter** [comment]
@sukhmel and @git-steve-git, thanks for reporting. This should be fixed in the latest release. If this bug is still present in the latest release, please feel free to create a new issue with up-to-date information.
